In [194]:
import pandas as pd
import numpy as np
from pathlib import Path
import seaborn as sns
import matplotlib.font_manager as fm
from matplotlib import pyplot as plt
import re

In [195]:
finrep = Path('../data/main/build/nfq/nfqcsv_reduced_modify_quarterly/N0000001.csv')
df = pd.read_csv(finrep)
finrep_columns = pd.read_csv(finrep, nrows=0).columns.tolist()

In [196]:
len(finrep_columns)

310

In [197]:
components = [col for col in finrep_columns]

In [198]:
BS_SISAN = []
BS_HUSAI = []
BS_JYUNSISAN = []
PL = []
CF = []

target = BS_SISAN
for comp in components:
    if comp == '流動負債':
        target = BS_HUSAI
    elif comp == '純資産合計／資本合計':
        target = BS_JYUNSISAN
    elif comp == '売上高・営業収益':
        target = PL
    elif comp == '税金等調整前当期純利益':
        target = CF
    target.append(comp)

In [199]:
print(len(BS_SISAN[2:]))
BS_SISAN[2:]

68

['流動資産',
 '売却目的保有資産',
 '現金・預金／現金及び現金同等物',
 '受取手形・売掛金及び契約資産／売掛金及びその他の短期債権',
 '非連結子会社関連会社\u3000受取手形・売掛金',
 'リース債権及びリース投資資産',
 '営業貸付金・営業投資有価証券',
 '有価証券',
 '棚卸資産',
 '商品・製品',
 '販売用不動産',
 '半製品・仕掛品',
 '原材料・貯蔵品',
 'その他棚卸資産',
 '前渡金',
 '返品資産',
 '前払費用',
 '未収入金',
 '未収収益',
 '短期貸付金',
 '預け金・関係会社預け金',
 '繰延税金資産',
 '金銭の信託',
 'デリバティブ債権',
 '繰延ヘッジ損失',
 '自己株式',
 'その他流動資産／その他の金融資産',
 '貸倒引当金（▲）',
 'その他引当金（▲）',
 '固定資産／非流動資産',
 '有形固定資産',
 '償却対象有形固定資産',
 '建物・構築物',
 '機械装置及び運搬具',
 '工具・器具及び備品',
 'リース資産',
 'その他償却対象有形固定資産',
 '建設仮勘定',
 '土地・その他非償却対象有形固定資産',
 '無形固定資産／無形資産',
 '営業権',
 '特許権・実用新案権',
 'ソフトウェア',
 'のれん',
 '商標権',
 '意匠権',
 'その他無形固定資産／その他無形資産',
 '投資・その他の資産合計',
 '投資有価証券・関係会社株式・出資金',
 '長期貸付金',
 '非連結子会社関連会社\u3000長期貸付金',
 '破産債権・更生債権・長期債権',
 '破産債権・更生債権',
 'その他長期債権・長期未収入金',
 '長期前払費用',
 '退職給付に係る資産（前払年金費用）',
 '投資不動産',
 '敷金・差入保証金',
 '再評価に係る繰延税金資産',
 'その他の投資・その他の資産／その他非流動資産',
 '投資損失引当金・その他引当金（▲）',
 '繰延資産',
 '社債発行差金',
 '開発費（旧：開発費・試験研究費）',
 'その他繰延資産',
 '連結調整勘定',
 '為替換算調整勘定',
 '資産合計']

In [200]:
print(len(BS_HUSAI))
BS_HUSAI

48

['流動負債',
 '支払手形・買掛金／買掛金及びその他の短期債務',
 '非連結子会社関連会社\u3000支払手形・買掛金',
 '短期借入金・社債合計',
 '１年内返済の借入金',
 '１年内償還の社債・転換社債',
 'リース債務',
 '未払金・未払費用',
 '未払賞与・給与／短期従業員給付',
 '未払法人税等',
 '未払事業所税',
 '未払消費税等',
 'デリバティブ債務（負債）',
 '繰延税金負債',
 '前受金',
 '契約負債',
 '返金負債',
 '預り金',
 '従業員預り金',
 '前受収益',
 '割賦販売未実現利益',
 '賞与引当金',
 '役員賞与引当金（未払役員報酬・賞与）',
 '債務保証損失引当金',
 'その他短期引当金',
 '設備関係支払手形',
 '設備関係未払金',
 '資産除去債務',
 'その他流動負債／その他の金融負債',
 '固定負債／非流動負債',
 '長期借入金・社債・転換社債',
 '社債・転換社債',
 '長期借入金',
 '非連結子会社関連会社\u3000長期借入金',
 '長期支払手形',
 '長期未払金',
 '引当金合計',
 '退職給付に係る負債（退職給付引当金）',
 '負ののれん',
 '再評価に係る繰延税金負債',
 'デリバティブ債務',
 '資産除去債務／資産除去債務引当金',
 '繰延ヘッジ利益',
 'その他固定負債／その他非流動負債／その他の負債',
 '特別法上の準備金・引当金',
 '負債合計',
 '償還可能非支配持分',
 '中間資本']

In [201]:
print(len(BS_JYUNSISAN))
BS_JYUNSISAN

27

['純資産合計／資本合計',
 '株主資本',
 '資本金',
 '新株式申込証拠金',
 '資本剰余金',
 '資本準備金',
 'その他資本剰余金',
 '資本金及び資本準備金減少差益',
 '自己株式処分差益',
 '利益剰余金',
 '利益準備金',
 'その他利益剰余金',
 '任意積立金',
 '繰越利益剰余金',
 '自己株式（▲）',
 '評価・換算差額等／累積その他の包括利益',
 'その他有価証券再評価差額金／金融資産の公正価値',
 '繰延ヘッジ損益／キャッシュフローヘッジ',
 '土地再評価差額金',
 '為替換算調整勘定／在外営業活動体の換算差額',
 '退職給付に係る調整累計額',
 '株式引受権',
 '新株予約権',
 '非支配株主持分／非支配持分',
 '負債・純資産合計／資本及び負債合計',
 '自己資本／親会社の所有者に帰属する資本',
 '年金負債調整額']

In [202]:
print(len(PL))
PL

54

['売上高・営業収益',
 '営業費用',
 '売上原価・営業原価',
 '割賦販売未実現利益・返品調整引当金差額／返品調整引当金差額',
 '売上総利益',
 '販売費及び一般管理費',
 '金融費用',
 '営業利益',
 '収益合計（性質別分類）',
 '費用合計（性質別分類）',
 '営業外収益',
 '受取利息・配当金',
 '有価証券売却益',
 '有価証券評価益',
 'デリバティブ評価益',
 'その他資産処分益・評価益',
 '為替差益',
 '負ののれん償却額',
 '持分法による投資利益',
 '投資事業組合・匿名組合関連利益',
 '賃貸料収入',
 'その他営業外収益',
 '営業外費用',
 '支払利息・割引料',
 '社債発行費・社債発行差金償却',
 '有価証券売却損',
 '有価証券評価損',
 'デリバティブ評価損',
 'その他資産処分損・評価損',
 '為替差損',
 '租税公課',
 'のれん償却額',
 '持分法による投資損失',
 '投資事業組合・匿名組合関連損失',
 '賃貸収入原価',
 'その他営業外費用',
 '経常利益／税金等調整前当期純利益',
 '特別利益',
 '事業・組織再編関連利益',
 '退職給付関連利益',
 '持分変動利益',
 '債務免除益',
 '引当金・準備金戻入・取崩額',
 '負ののれん発生益',
 'その他特別利益',
 '特別損失',
 '事業・組織再編関連損',
 '減損損失',
 '減価償却費',
 '退職給付関連費用',
 '持分変動損失',
 '引当金・準備金繰入額',
 'その他特別損失',
 '匿名組合損益分配額']

In [203]:
print(len(CF))
CF

111

['税金等調整前当期純利益',
 '特別法上の準備金・引当金取崩額',
 '特別法上の準備金・引当金繰入額',
 '税金等調整前当期利益',
 '法人税等',
 '継続事業からの純利益',
 '非継続事業からの純利益',
 '法人税・住民税及び事業税合計／当期税金費用',
 '法人税等調整額／繰延税金費用',
 '過年度法人税等追徴・還付額',
 '当期純利益（連結）',
 '非支配株主に帰属する当期純利益',
 '旧：連結調整勘定償却額',
 '為替換算調整',
 'その他の当期利益影響額',
 '親会社株主に帰属する当期純利益（連結）／当期利益（単独）',
 'その他の償却費',
 '繰延税金',
 '有価証券及び投資有価証券売却損益（▲益）',
 '有価証券評価損益（▲益）',
 'デリバティブ評価損益（▲益）',
 '固定資産売却損益（▲益）',
 '固定資産除却損益（▲益）',
 '固定資産評価損益（▲益）',
 'その他の評価損益（▲益）',
 '社債発行差金償却額',
 'のれん・負ののれん償却額',
 '貸倒引当金の増加額（▲減）',
 '退職給付及び役員退職慰労引当金の増減額（▲減）',
 '賞与引当金の増加額（▲減）',
 'その他の引当金の増加額（▲減）',
 '受取利息及び受取配当金（▲）',
 '支払利息',
 '為替差損（▲益）',
 '非支配株主損益',
 '持分法による投資損益（▲益）',
 '損害賠償損失（▲益）',
 '事業・組織再編関連損益（▲益）',
 '売上債権の減少額（▲増）',
 '棚卸資産の減少額（▲増）',
 '仕入債務の増加額（▲減）',
 '未払消費税等の増加額（▲減）',
 '割引手形の増加額（▲減）',
 'その他の流動資産の減少額（▲増）',
 'その他の流動負債の増加額（▲減）',
 '役員賞与の支払額（▲）',
 'その他の小計欄より上の営業キャッシュフロー',
 '営業収入',
 '原材料及び商品の仕入支出（▲）',
 '人件費支出（▲）',
 'その他の営業支出（▲）',
 '小計',
 '利息及び配当金の受取額',
 '利息の支払額（▲）',
 '法人税等の支払額（▲）',
 '損害賠償金の支払額（▲）',
 'その他の小計欄以降の営業キャッシュフロー',
 '営業活動によるキャッシュフロー',
 '日経調整営業キャッシュフロー',
 '定期預金の預入による支出（▲）',
 '定期預金の払戻による収入',
 '固定資産の取得による支出（▲）',
 '有形固定資産の取得による支出（▲）',
 '無形固定資産の取得による支出（▲）',
 '投資その他の資産の取得による支出（▲）',
 '固定資産の売却による収入',
 '有形固定資産の売却による収入',
 '無形固定資産の売却による収入',
 '投資その他の資産の売却による収入',
 '有価証券の取得による支出（▲）',
 '有価証券の売却による収入',
 '投資有価証券の取得による支出（▲）',
 '投資有価証券の売却による収入',
 '子会社・関係会社株式取得（▲）',
 '子会社・関係会社株式売却',
 '貸付金の増加による支出（▲）',
 '貸付金の回収による収入',
 'その他の投資活動によるキャッシュフロー',
 '投資活動によるキャッシュフロー',
 '日経調整投資キャッシュフロー',
 '短期借入金による収入',
 '短期借入金の返済による支出（▲）',
 'リース債務の返済（▲）',
 'コマーシャルペーパーによる調達額',
 'コマーシャルペーパー返済額（▲）',
 '長期借入金による収入',
 '長期借入金の返済による支出（▲）',
 '社債の発行による収入',
 '社債の償還による支出（▲）',
 '株式の発行による収入',
 '自己株式の取得による支出（▲）',
 '自己株式の処分による収入',
 '利息の支払金額（▲）',
 '配当金の支払金額（▲）',
 '非支配株主からの払い込みによる収入',
 '非支配株主への配当金の支払額（▲）',
 'その他の財務活動によるキャッシュフロー',
 '財務活動によるキャッシュフロー',
 '日経調整財務キャッシュフロー',
 '現金及び現金同等物に関わる換算差額',
 '現金及び現金同等物の増加額（▲減）',
 '現金及び現金同等物の期首残高',
 'その他の変更による影響額',
 '現金及び現金同等物の期末残高',
 '現金及び預金',
 '預入期間が３ヵ月を超える定期預金（▲）',
 'コマーシャルペーパー',
 '譲渡性預金',
 '売り戻し条件付き現先',
 '公社債投信',
 'その他現金及び現金同等物']

In [204]:
[col for col in finrep_columns if 'うち' in col]

[]

In [205]:
finrep_columns_sorted = sorted(finrep_columns, key=lambda x: (len(x), x))

dict_col_include_name = {}
for col in finrep_columns_sorted:
    if '.1' in col:
        col = col[:-2]
    if col not in dict_col_include_name:
        dict_col_include_name[col] = []
    for target_col in finrep_columns_sorted:
        if col != target_col and re.search(re.escape(col), target_col):
            dict_col_include_name[col].append(target_col)

print(len(dict_col_include_name))
dict_col_include_name

310

{'小計': ['その他の小計欄以降の営業キャッシュフロー', 'その他の小計欄より上の営業キャッシュフロー'],
 'のれん': ['負ののれん', 'のれん償却額', '負ののれん償却額', '負ののれん発生益', 'のれん・負ののれん償却額'],
 '前受金': [],
 '前渡金': [],
 '商標権': [],
 '営業権': [],
 '意匠権': [],
 '資本金': ['資本金及び資本準備金減少差益'],
 '預り金': ['従業員預り金'],
 '中間資本': [],
 '前受収益': [],
 '前払費用': ['長期前払費用'],
 '営業利益': [],
 '営業収入': [],
 '営業費用': [],
 '契約負債': [],
 '支払利息': ['支払利息・割引料'],
 '有価証券': ['有価証券売却損',
  '有価証券売却益',
  '有価証券評価損',
  '有価証券評価益',
  '有価証券の売却による収入',
  '有価証券評価損益（▲益）',
  '営業貸付金・営業投資有価証券',
  '投資有価証券の売却による収入',
  '有価証券の取得による支出（▲）',
  '投資有価証券の取得による支出（▲）',
  '投資有価証券・関係会社株式・出資金',
  '有価証券及び投資有価証券売却損益（▲益）',
  'その他有価証券再評価差額金／金融資産の公正価値'],
 '未収入金': ['その他長期債権・長期未収入金'],
 '未収収益': [],
 '株主資本': [],
 '棚卸資産': ['その他棚卸資産', '棚卸資産の減少額（▲増）'],
 '法人税等': ['未払法人税等', '法人税等の支払額（▲）', '過年度法人税等追徴・還付額', '法人税等調整額／繰延税金費用'],
 '流動負債': ['固定負債／非流動負債',
  'その他の流動負債の増加額（▲減）',
  'その他流動負債／その他の金融負債',
  'その他固定負債／その他非流動負債／その他の負債'],
 '流動資産': ['固定資産／非流動資産',
  'その他の流動資産の減少額（▲増）',
  'その他流動資産／その他の金融資産',
  'その他の投資・その他の資産／その他非流動資産'],
 '減損損失': [],
 '為替差損': ['為替差損（▲益）'],
 '為替差益': [],
 '特別利益': ['その他特別利益'],
 '特別損失': ['その他特別損失'],
 '租税公課': [],
 '繰延税金': ['繰延税金負債',
  '繰延税金資産',
  '再評価に係る繰延税金負債',
  '再評価に係る繰延税金資産',
  '法人税等調整額／繰延税金費用'],
 '繰延資産': ['その他繰延資産'],
 '自己株式': ['自己株式（▲）', '自己株式処分差益', '自己株式の処分による収入', '自己株式の取得による支出（▲）'],
 '負債合計': ['負債・純資産合計／資本及び負債合計'],
 '資産合計': ['純資産合計／資本合計', '投資・その他の資産合計', '負債・純資産合計／資本及び負債合計'],
 '返品資産': [],
 '返金負債': [],
 '金融費用': [],
 'リース債務': ['リース債務の返済（▲）'],
 'リース資産': [],
 '任意積立金': [],
 '債務免除益': [],
 '公社債投信': [],
 '利益剰余金': ['繰越利益剰余金', 'その他利益剰余金'],
 '利益準備金': [],
 '商品・製品': [],
 '営業外収益': ['その他営業外収益'],
 '営業外費用': ['その他営業外費用'],
 '売上総利益': [],
 '建設仮勘定': [],
 '引当金合計': [],
 '投資不動産': [],
 '新株予約権': [],
 '株式引受権': [],
 '決算発表日': [],
 '減価償却費': [],
 '短期貸付金': [],
 '譲渡性預金': [],
 '負ののれん': ['負ののれん償却額', '負ののれん発生益', 'のれん・負ののれん償却額'],
 '賃貸料収入': [],
 '資本剰余金': ['その他資本剰余金'],
 '資本準備金': ['資本金及び資本準備金減少差益'],
 '賞与引当金': ['賞与引当金の増加額（▲減）', '役員賞与引当金（未払役員報酬・賞与）'],
 '金銭の信託': [],
 '長期借入金': ['長期借入金による収入',
  '長期借入金・社債・転換社債',
  '長期借入金の返済による支出（▲）',
  '非連結子会社関連会社\u3000長期借入金'],
 '長期未払金': [],
 '長期貸付金': ['非連結子会社関連会社\u3000長期貸付金'],
 'Ticker': [],
 'のれん償却額': ['負ののれん償却額', 'のれん・負ののれん償却額'],
 'ソフトウェア': [],
 '建物・構築物': [],
 '従業員預り金': [],
 '持分変動利益': [],
 '持分変動損失': [],
 '有形固定資産': ['償却対象有形固定資産',
  'その他償却対象有形固定資産',
  '有形固定資産の売却による収入',
  '土地・その他非償却対象有形固定資産',
  '有形固定資産の取得による支出（▲）'],
 '未払事業所税': [],
 '未払法人税等': [],
 '未払消費税等': ['未払消費税等の増加額（▲減）'],
 '為替換算調整': ['為替換算調整勘定', '為替換算調整勘定／在外営業活動体の換算差額'],
 '現金及び預金': [],
 '社債発行差金': ['社債発行差金償却額', '社債発行費・社債発行差金償却'],
 '繰延税金負債': ['再評価に係る繰延税金負債'],
 '繰延税金資産': ['再評価に係る繰延税金資産'],
 '販売用不動産': [],
 '賃貸収入原価': [],
 '資産除去債務': ['資産除去債務／資産除去債務引当金'],
 '連結調整勘定': ['旧：連結調整勘定償却額'],
 '長期前払費用': [],
 '長期支払手形': [],
 'その他の償却費': [],
 'その他棚卸資産': [],
 'その他特別利益': [],
 'その他特別損失': [],
 'その他繰延資産': [],
 '半製品・仕掛品': [],
 '原材料・貯蔵品': [],
 '年金負債調整額': [],
 '有価証券売却損': ['有価証券及び投資有価証券売却損益（▲益）'],
 '有価証券売却益': [],
 '有価証券評価損': ['有価証券評価損益（▲益）'],
 '有価証券評価益': [],
 '社債・転換社債': ['長期借入金・社債・転換社債', '１年内償還の社債・転換社債'],
 '繰延ヘッジ利益': [],
 '繰延ヘッジ損失': [],
 '繰越利益剰余金': [],
 '自己株式（▲）': [],
 '設備関係未払金': [],
 '非支配株主損益': [],
 'その他利益剰余金': [],
 'その他営業外収益': [],
 'その他営業外費用': [],
 'その他短期引当金': [],
 'その他資本剰余金': [],
 'デリバティブ債務': ['デリバティブ債務（負債）'],
 'デリバティブ債権': [],
 '人件費支出（▲）': [],
 '受取利息・配当金': [],
 '土地再評価差額金': [],
 '売上高・営業収益': [],
 '売却目的保有資産': [],
 '支払利息・割引料': [],
 '敷金・差入保証金': [],
 '新株式申込証拠金': [],
 '未払金・未払費用': [],
 '為替差損（▲益）': [],
 '為替換算調整勘定': ['為替換算調整勘定／在外営業活動体の換算差額'],
 '自己株式処分差益': [],
 '設備関係支払手形': [],
 '負ののれん償却額': ['のれん・負ののれん償却額'],
 '負ののれん発生益': [],
 '貸倒引当金（▲）': [],
 '退職給付関連利益': [],
 '退職給付関連費用': [],
 'その他引当金（▲）': ['投資損失引当金・その他引当金（▲）'],
 'デリバティブ評価損': ['デリバティブ評価損益（▲益）'],
 'デリバティブ評価益': [],
 '債務保証損失引当金': [],
 '償還可能非支配持分': [],
 '利息の支払額（▲）': [],
 '割賦販売未実現利益': ['割賦販売未実現利益・返品調整引当金差額／返品調整引当金差額'],
 '匿名組合損益分配額': [],
 '売上原価・営業原価': [],
 '工具・器具及び備品': [],
 '当期純利益（連結）': ['親会社株主に帰属する当期純利益（連結）／当期利益（単独）'],
 '機械装置及び運搬具': [],
 '特許権・実用新案権': [],
 '破産債権・更生債権': ['破産債権・更生債権・長期債権'],
 '社債発行差金償却額': [],
 '１年内返済の借入金': [],
 'コマーシャルペーパー': ['コマーシャルペーパーによる調達額', 'コマーシャルペーパー返済額（▲）'],
 '事業・組織再編関連損': ['事業・組織再編関連損益（▲益）'],
 '償却対象有形固定資産': ['その他償却対象有形固定資産', '土地・その他非償却対象有形固定資産'],
 '利息の支払金額（▲）': [],
 '固定負債／非流動負債': [],
 '固定資産／非流動資産': [],
 '売り戻し条件付き現先': [],
 '引当金・準備金繰入額': [],
 '持分法による投資利益': [],
 '持分法による投資損失': [],
 '損害賠償損失（▲益）': [],
 '株式の発行による収入': [],
 '短期借入金による収入': [],
 '短期借入金・社債合計': [],
 '社債の発行による収入': [],
 '税金等調整前当期利益': [],
 '純資産合計／資本合計': [],
 '継続事業からの純利益': ['非継続事業からの純利益'],
 '販売費及び一般管理費': [],
 '長期借入金による収入': [],
 'その他の営業支出（▲）': [],
 'その他の当期利益影響額': [],
 'リース債務の返済（▲）': [],
 '事業・組織再編関連利益': [],
 '利息及び配当金の受取額': [],
 '収益合計（性質別分類）': [],
 '役員賞与の支払額（▲）': [],
 '投資・その他の資産合計': [],
 '旧：連結調整勘定償却額': [],
 '法人税等の支払額（▲）': [],
 '無形固定資産／無形資産': [],
 '税金等調整前当期純利益': ['経常利益／税金等調整前当期純利益'],
 '貸付金の回収による収入': [],
 '費用合計（性質別分類）': [],
 '配当金の支払金額（▲）': [],
 '非継続事業からの純利益': [],
 '預け金・関係会社預け金': [],
 'その他の変更による影響額': [],
 'その他の評価損益（▲益）': [],
 'その他現金及び現金同等物': [],
 'その他資産処分損・評価損': [],
 'その他資産処分益・評価益': [],
 'のれん・負ののれん償却額': [],
 'デリバティブ債務（負債）': [],
 '仕入債務の増加額（▲減）': [],
 '再評価に係る繰延税金負債': [],
 '再評価に係る繰延税金資産': [],
 '割引手形の増加額（▲減）': [],
 '固定資産の売却による収入': ['有形固定資産の売却による収入', '無形固定資産の売却による収入'],
 '固定資産売却損益（▲益）': [],
 '固定資産評価損益（▲益）': [],
 '固定資産除却損益（▲益）': [],
 '売上債権の減少額（▲増）': [],
 '子会社・関係会社株式売却': [],
 '定期預金の払戻による収入': [],
 '損害賠償金の支払額（▲）': [],
 '有価証券の売却による収入': ['投資有価証券の売却による収入'],
 '有価証券評価損益（▲益）': [],
 '棚卸資産の減少額（▲増）': [],
 '特別法上の準備金・引当金': ['特別法上の準備金・引当金取崩額', '特別法上の準備金・引当金繰入額'],
 '自己株式の処分による収入': [],
 '退職給付に係る調整累計額': [],
 'その他償却対象有形固定資産': [],
 '引当金・準備金戻入・取崩額': [],
 '社債の償還による支出（▲）': [],
 '貸倒引当金の増加額（▲減）': [],
 '賞与引当金の増加額（▲減）': [],
 '過年度法人税等追徴・還付額': [],
 '長期借入金・社債・転換社債': [],
 '非支配株主持分／非支配持分': [],
 '１年内償還の社債・転換社債': [],
 'その他長期債権・長期未収入金': [],
 'デリバティブ評価損益（▲益）': [],
 'リース債権及びリース投資資産': [],
 '受取利息及び受取配当金（▲）': [],
 '営業貸付金・営業投資有価証券': [],
 '投資有価証券の売却による収入': [],
 '持分法による投資損益（▲益）': [],
 '日経調整営業キャッシュフロー': [],
 '日経調整投資キャッシュフロー': [],
 '日経調整財務キャッシュフロー': [],
 '有形固定資産の売却による収入': [],
 '未払消費税等の増加額（▲減）': [],
 '法人税等調整額／繰延税金費用': [],
 '無形固定資産の売却による収入': [],
 '現金及び現金同等物の期末残高': [],
 '現金及び現金同等物の期首残高': [],
 '破産債権・更生債権・長期債権': [],
 '社債発行費・社債発行差金償却': [],
 '貸付金の増加による支出（▲）': [],
 '資本金及び資本準備金減少差益': [],
 'その他の引当金の増加額（▲減）': [],
 '事業・組織再編関連損益（▲益）': [],
 '原材料及び商品の仕入支出（▲）': [],
 '営業活動によるキャッシュフロー': [],
 '固定資産の取得による支出（▲）': ['有形固定資産の取得による支出（▲）', '無形固定資産の取得による支出（▲）'],
 '子会社・関係会社株式取得（▲）': [],
 '定期預金の預入による支出（▲）': [],
 '投資事業組合・匿名組合関連利益': [],
 '投資事業組合・匿名組合関連損失': [],
 '投資活動によるキャッシュフロー': ['その他の投資活動によるキャッシュフロー'],
 '有価証券の取得による支出（▲）': ['投資有価証券の取得による支出（▲）'],
 '未払賞与・給与／短期従業員給付': [],
 '特別法上の準備金・引当金取崩額': [],
 '特別法上の準備金・引当金繰入額': [],
 '現金・預金／現金及び現金同等物': [],
 '自己株式の取得による支出（▲）': [],
 '財務活動によるキャッシュフロー': ['その他の財務活動によるキャッシュフロー'],
 '非支配株主に帰属する当期純利益': [],
 'その他の流動負債の増加額（▲減）': [],
 'その他の流動資産の減少額（▲増）': [],
 'その他流動負債／その他の金融負債': [],
 'その他流動資産／その他の金融資産': [],
 'コマーシャルペーパーによる調達額': [],
 'コマーシャルペーパー返済額（▲）': [],
 '投資その他の資産の売却による収入': [],
 '短期借入金の返済による支出（▲）': [],
 '経常利益／税金等調整前当期純利益': [],
 '資産除去債務／資産除去債務引当金': [],
 '長期借入金の返済による支出（▲）': [],
 '開発費（旧：開発費・試験研究費）': [],
 '非連結子会社関連会社\u3000長期借入金': [],
 '非連結子会社関連会社\u3000長期貸付金': [],
 'その他無形固定資産／その他無形資産': [],
 '土地・その他非償却対象有形固定資産': [],
 '投資損失引当金・その他引当金（▲）': [],
 '投資有価証券の取得による支出（▲）': [],
 '投資有価証券・関係会社株式・出資金': [],
 '有形固定資産の取得による支出（▲）': [],
 '無形固定資産の取得による支出（▲）': [],
 '現金及び現金同等物に関わる換算差額': [],
 '現金及び現金同等物の増加額（▲減）': [],
 '負債・純資産合計／資本及び負債合計': [],
 '退職給付に係る資産（前払年金費用）': [],
 '非支配株主からの払い込みによる収入': [],
 '非支配株主への配当金の支払額（▲）': [],
 '役員賞与引当金（未払役員報酬・賞与）': [],
 '退職給付に係る負債（退職給付引当金）': [],
 'その他の投資活動によるキャッシュフロー': [],
 'その他の財務活動によるキャッシュフロー': [],
 '投資その他の資産の取得による支出（▲）': [],
 '繰延ヘッジ損益／キャッシュフローヘッジ': [],
 '自己資本／親会社の所有者に帰属する資本': [],
 '評価・換算差額等／累積その他の包括利益': [],
 '非連結子会社関連会社\u3000受取手形・売掛金': [],
 '非連結子会社関連会社\u3000支払手形・買掛金': [],
 '預入期間が３ヵ月を超える定期預金（▲）': [],
 'その他の小計欄以降の営業キャッシュフロー': [],
 '有価証券及び投資有価証券売却損益（▲益）': [],
 'その他の小計欄より上の営業キャッシュフロー': [],
 '法人税・住民税及び事業税合計／当期税金費用': [],
 '為替換算調整勘定／在外営業活動体の換算差額': [],
 'その他の投資・その他の資産／その他非流動資産': [],
 '支払手形・買掛金／買掛金及びその他の短期債務': [],
 'その他固定負債／その他非流動負債／その他の負債': [],
 'その他有価証券再評価差額金／金融資産の公正価値': [],
 '退職給付及び役員退職慰労引当金の増減額（▲減）': [],
 '受取手形・売掛金及び契約資産／売掛金及びその他の短期債権': [],
 '親会社株主に帰属する当期純利益（連結）／当期利益（単独）': [],
 '割賦販売未実現利益・返品調整引当金差額／返品調整引当金差額': []}

In [206]:
print(len(df))
# df[['のれん', '負ののれん', 'のれん償却額', '負ののれん償却額', '負ののれん発生益', 'のれん・負ののれん償却額']]
df.loc[df['のれん償却額'].isna(), 'のれん償却額'] = df.loc[df['のれん償却額'].isna(), 'のれん・負ののれん償却額'] - df.loc[df['のれん償却額'].isna(), '負ののれん償却額']

91

In [207]:
df[['有価証券', '有価証券評価益', '有価証券評価益', '有価証券評価損益（▲益）']].count()

有価証券             1
有価証券評価益          1
有価証券評価益          1
有価証券評価損益（▲益）    75
dtype: int64

In [208]:
df[['有価証券', '有価証券売却益', '有価証券売却損','有価証券の売却による収入', '有価証券及び投資有価証券売却損益（▲益）', ]].count()

有価証券                     1
有価証券売却益                 91
有価証券売却損                 36
有価証券の売却による収入             4
有価証券及び投資有価証券売却損益（▲益）    65
dtype: int64

In [209]:
df[['有価証券', '有価証券売却益', '有価証券売却損','有価証券の売却による収入', '有価証券及び投資有価証券売却損益（▲益）', ]].tail(20)

    有価証券  有価証券売却益  有価証券売却損  有価証券の売却による収入  有価証券及び投資有価証券売却損益（▲益）
71   NaN      0.0      NaN           NaN                 -43.0
72   NaN      0.0      NaN           NaN                 -43.0
73   NaN     12.0      NaN           NaN                 -43.0
74   NaN      1.0      NaN           NaN                 -13.0
75   NaN      0.0      NaN           NaN                 -13.0
76   NaN   1267.0      NaN           NaN               -1267.0
77   NaN      1.0      NaN           NaN               -1267.0
78   NaN      0.0      NaN           NaN               -1268.0
79   NaN      0.0      NaN           NaN                   NaN
80   NaN      0.0      NaN           NaN                   NaN
81   NaN      0.0      NaN           NaN                   NaN
82   NaN      0.0      NaN           NaN                   NaN
83   NaN      0.0      NaN           NaN                   NaN
84   NaN      0.0      NaN           NaN                   NaN
85   NaN      0.0      NaN           NaN                   NaN
86   NaN      0.0      NaN           NaN                   NaN
87   NaN      0.0      NaN           NaN               -1267.0
88   NaN      0.0      NaN           NaN               -1267.0
89   NaN      8.0      NaN           NaN               -1267.0
90   NaN      0.0      NaN           NaN                  -8.0

In [210]:
tmp_l = ['有価証券',
  '有価証券売却損',
  '有価証券売却益',
  '有価証券評価損',
  '有価証券評価益',
  '有価証券の売却による収入',
  '有価証券評価損益（▲益）',
  '営業貸付金・営業投資有価証券',
  '投資有価証券の売却による収入',
  '有価証券の取得による支出（▲）',
  '投資有価証券の取得による支出（▲）',
  '投資有価証券・関係会社株式・出資金',
  '有価証券及び投資有価証券売却損益（▲益）',
  'その他有価証券再評価差額金／金融資産の公正価値']

df[tmp_l].count()

有価証券                        1
有価証券売却損                    36
有価証券売却益                    91
有価証券評価損                    91
有価証券評価益                     1
有価証券の売却による収入                4
有価証券評価損益（▲益）               75
営業貸付金・営業投資有価証券              0
投資有価証券の売却による収入             83
有価証券の取得による支出（▲）             1
投資有価証券の取得による支出（▲）          91
投資有価証券・関係会社株式・出資金          91
有価証券及び投資有価証券売却損益（▲益）       65
その他有価証券再評価差額金／金融資産の公正価値    88
dtype: int64

In [211]:
df[tmp_l].corr()

,有価証券,有価証券売却損,有価証券売却益,有価証券評価損,有価証券評価益,有価証券の売却による収入,有価証券評価損益（▲益）,営業貸付金・営業投資有価証券,投資有価証券の売却による収入,有価証券の取得による支出（▲）,投資有価証券の取得による支出（▲）,投資有価証券・関係会社株式・出資金,有価証券及び投資有価証券売却損益（▲益）,その他有価証券再評価差額金／金融資産の公正価値
有価証券,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
有価証券売却損,NaN,1.000000,-0.054371,0.116201,NaN,-1.000000,0.117094,NaN,0.124646,NaN,-0.656601,-0.388114,0.655725,-0.452028
有価証券売却益,NaN,-0.054371,1.000000,-0.000857,NaN,0.449050,0.033722,NaN,0.177942,NaN,0.077834,0.035169,-0.348817,0.062206
有価証券評価損,NaN,0.116201,-0.000857,1.000000,NaN,0.455088,0.221474,NaN,0.024182,NaN,0.002774,-0.000282,-0.019340,0.033315
有価証券評価益,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
有価証券の売却による収入,NaN,-1.000000,0.449050,0.455088,NaN,1.000000,0.776132,NaN,-0.508281,NaN,0.773292,0.021693,-0.946282,1.000000
有価証券評価損益（▲益）,NaN,0.117094,0.033722,0.221474,NaN,0.776132,1.000000,NaN,-0.086862,NaN,-0.047794,-0.132007,0.191330,-0.286825
営業貸付金・営業投資有価証券,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
投資有価証券の売却による収入,NaN,0.124646,0.177942,0.024182,NaN,-0.508281,-0.086862,NaN,1.000000,NaN,0.227906,0.263411,-0.481693,0.415328
有価証券の取得による支出（▲）,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
投資有価証券の取得による支出（▲）,NaN,-0.656601,0.077834,0.002774,NaN,0.773292,-0.047794,NaN,0.227906,NaN,1.000000,0.115527,-0.315210,0.219979
投資有価証券・関係会社株式・出資金,NaN,-0.388114,0.035169,-0.000282,NaN,0.021693,-0.132007,NaN,0.263411,NaN,0.115527,1.000000,-0.580573,0.937428
有価証券及び投資有価証券売却損益（▲益）,NaN,0.655725,-0.348817,-0.019340,NaN,-0.946282,0.191330,NaN,-0.481693,NaN,-0.315210,-0.580573,1.000000,-0.687517
その他有価証券再評価差額金／金融資産の公正価値,NaN,-0.452028,0.062206,0.033315,NaN,1.000000,-0.286825,NaN,0.415328,NaN,0.219979,0.937428,-0.687517,1.000000

In [212]:
[col for col in df.columns if '経常利益' in col]

['経常利益／税金等調整前当期純利益']