In [1]:
import pandas as pd
import numpy as np
from pathlib import Path

In [2]:
csv = Path('../data/main/master/product/weekly_remodify_fundamental_all.csv')
big_df = pd.read_csv(csv)
cols = big_df.columns.tolist()
len(cols)

FileNotFoundError: [Errno 2] No such file or directory: '..\\data\\main\\master\\product\\weekly_remodify_fundamental_all.csv'

## ラベルの調査

In [ ]:
mask = big_df.iloc[:, 2:].notnull().any(axis=1)
big_df['上場フラグ'] = 0
big_df.loc[mask, '上場フラグ'] = 1

In [ ]:
print(big_df['上場フラグ'].value_counts())

上場フラグ
0    3967826
1    1557166
Name: count, dtype: int64

In [ ]:
# for col in cols:
#     notnull_ratio = big_df.loc[big_df['上場フラグ'] == 1, col].notnull().sum() / len(big_df.loc[big_df['上場フラグ'] == 1])
#     print(f'Column: {col}, Not Null Ratio (上場フラグ=1): {notnull_ratio:.4f}')

In [ ]:
delete_cols = [
    '売却目的保有資産',
    '非連結子会社関連会社　受取手形・売掛金',
    'リース債権及びリース投資資産',
    '営業貸付金・営業投資有価証券',
    '販売用不動産',
    'その他棚卸資産',
    '返品資産',
    '未収収益',
    '預け金・関係会社預け金',
    '金銭の信託',
    'デリバティブ債権',
    '繰延ヘッジ損失',
    '自己株式',
    'その他引当金（▲）',
    '営業権',
    '特許権・実用新案権',
    '商標権',
    '意匠権',
    '非連結子会社関連会社　長期貸付金',
    '破産債権・更生債権',
    'その他長期債権・長期未収入金',
    '投資不動産',
    '再評価に係る繰延税金資産',
    '投資損失引当金・その他引当金（▲）',
    '繰延資産',
    '社債発行差金',
    '開発費（旧：開発費・試験研究費）',
    'その他繰延資産',
    '連結調整勘定',
    '為替換算調整勘定',
    '非連結子会社関連会社　支払手形・買掛金',
    '未払賞与・給与／短期従業員給付',
    '未払事業所税',
    'デリバティブ債務（負債）',
    '契約負債',
    '返金負債',
    '従業員預り金',
    '割賦販売未実現利益',
    '債務保証損失引当金',
    '設備関係未払金',
    '資産除去債務',
    '非連結子会社関連会社　長期借入金',
    '長期支払手形',
    '負ののれん',
    'デリバティブ債務',
    '繰延ヘッジ利益',
    '特別法上の準備金・引当金',
    '償還可能非支配持分',
    '中間資本',
    '新株式申込証拠金',
    '資本金及び資本準備金減少差益',
    '自己株式処分差益',
    '株式引受権',
    '年金負債調整額',
    '割賦販売未実現利益・返品調整引当金差額／返品調整引当金差額',
    '金融費用',
    '収益合計（性質別分類）',
    '費用合計（性質別分類）',
    '有価証券評価益',
    'デリバティブ評価益',
    '為替差益',
    '負ののれん償却額',
    '投資事業組合・匿名組合関連利益',
    '社債発行費・社債発行差金償却',
    'デリバティブ評価損',
    '為替差損',
    '租税公課',
    'のれん償却額',
    '投資事業組合・匿名組合関連損失',
    '賃貸収入原価',
    '退職給付関連利益',
    '持分変動利益',
    '債務免除益',
    '引当金・準備金戻入・取崩額',
    '負ののれん発生益',
    '事業・組織再編関連損',
    '持分変動損失',
    '匿名組合損益分配額',
    '特別法上の準備金・引当金取崩額',
    '特別法上の準備金・引当金繰入額',
    '継続事業からの純利益',
    '非継続事業からの純利益',
    '過年度法人税等追徴・還付額',
    '旧：連結調整勘定償却額',
    '為替換算調整',
    'その他の当期利益影響額',
    'その他の償却費',
    '繰延税金',
    'デリバティブ評価損益（▲益）',
    '固定資産評価損益（▲益）',
    'その他の評価損益（▲益）',
    '社債発行差金償却額',
    '非支配株主損益',
    '損害賠償損失（▲益）',
    '事業・組織再編関連損益（▲益）',
    '割引手形の増加額（▲減）',
    '役員賞与の支払額（▲）',
    '営業収入',
    '原材料及び商品の仕入支出（▲）',
    '人件費支出（▲）',
    'その他の営業支出（▲）',
    '利息及び配当金の受取額',
    '損害賠償金の支払額（▲）',
    '有価証券の取得による支出（▲）',
    '子会社・関係会社株式売却',
    'コマーシャルペーパーによる調達額',
    'コマーシャルペーパー返済額（▲）',
    '社債の発行による収入',
    '利息の支払金額（▲）',
    '非支配株主からの払い込みによる収入',
    'コマーシャルペーパー',
    '譲渡性預金',
    '売り戻し条件付き現先',
    '公社債投信'
]

In [ ]:
dropped_under10PctCols_big_df = big_df.drop(columns=delete_cols)

In [ ]:
x = dropped_under10PctCols_big_df.drop(columns=['nikkei', 'week_id'])
x.fillna(0, inplace=True)
vif = np.diag(np.linalg.inv(x.corr().values))
df_vif = pd.DataFrame(vif)
df_vif.columns = ["VIF"]
df_vif.index = x.corr().columns
df_vif.sort_values("VIF")

                           VIF
無形固定資産の売却による収入        1.012104
自己株式の処分による収入          1.051012
未払消費税等の増加額（▲減）        1.061678
リース資産                 1.065713
設備関係支払手形              1.086174
...                        ...
資産合計              48016.323502
日経調整投資キャッシュフロー    90284.013380
投資活動によるキャッシュフロー   90445.076952
日経調整営業キャッシュフロー   111455.405979
営業活動によるキャッシュフロー  111819.630400

[195 rows x 1 columns]

In [ ]:
df_vif.to_csv('./vif_after_dropping_under10PctCols.csv', index=True)

In [ ]:
df_vif.sort_values("VIF", inplace=True)
under_10vif_df = df_vif[df_vif['VIF'] < 10]
upper_10vif_df = df_vif[df_vif['VIF'] >= 10]

In [ ]:
under_10vif_df.to_csv('./under_10vif_cols.csv', index=True)
upper_10vif_df.to_csv('./upper_10vif_cols.csv', index=True)

In [ ]:
Pct_100_columns = [
    '固定資産の取得による支出（▲）',
    '有形固定資産の取得による支出（▲）',
    '無形固定資産の取得による支出（▲）',
    '投資その他の資産の取得による支出（▲）',
    '固定資産の売却による収入',
    '有形固定資産の売却による収入',
    '無形固定資産の売却による収入',
    '投資その他の資産の売却による収入',
    '売上高・営業収益',
    '上場フラグ'
]

In [ ]:
test_df = dropped_under10PctCols_big_df.copy()
test_df[test_df[Pct_100_columns[:-1]] == 0] = np.nan

In [ ]:
test_df[Pct_100_columns[:-1]].count() / len(test_df[Pct_100_columns[-1]] == 1)

固定資産の取得による支出（▲）        0.267316
有形固定資産の取得による支出（▲）      0.233954
無形固定資産の取得による支出（▲）      0.180210
投資その他の資産の取得による支出（▲）    0.086467
固定資産の売却による収入           0.196928
有形固定資産の売却による収入         0.131035
無形固定資産の売却による収入         0.004505
投資その他の資産の売却による収入       0.074977
売上高・営業収益               0.276053
dtype: float64

In [ ]:
new_delete_cols = [
    '投資その他の資産の取得による支出（▲）',
    '無形固定資産の売却による収入',
    '投資その他の資産の売却による収入'
]

In [ ]:
slim_df = dropped_under10PctCols_big_df.drop(columns=new_delete_cols)

In [ ]:
slim_df

,nikkei,week_id,流動資産,現金・預金／現金及び現金同等物,受取手形・売掛金及び契約資産／売掛金及びその他の短期債権,有価証券,棚卸資産,商品・製品,半製品・仕掛品,原材料・貯蔵品,...,日経調整財務キャッシュフロー,現金及び現金同等物に関わる換算差額,現金及び現金同等物の増加額（▲減）,現金及び現金同等物の期首残高,その他の変更による影響額,現金及び現金同等物の期末残高,現金及び預金,預入期間が３ヵ月を超える定期預金（▲）,その他現金及び現金同等物,上場フラグ
0,N0000001,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
1,N0000002,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
2,N0000003,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
3,N0000004,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
4,N0000005,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5524987,N0091164,1198,15838.0,9092.0,3681.0,100.0,2575.0,NaN,761.0,NaN,...,-225.0,414.0,1454.0,7061.0,NaN,8516.0,8612.0,-196.0,NaN,1
5524988,N0091165,1198,6610.0,3828.0,1453.0,50.0,2072.0,1175.0,52.0,441.0,...,-480.0,NaN,-1395.0,3224.0,NaN,1828.0,3828.0,-2000.0,NaN,1
5524989,N0091290,1198,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
5524990,N0091517,1198,63718.0,21299.0,9878.0,NaN,26248.0,25970.0,NaN,NaN,...,-2454.0,355.0,4927.0,16343.0,NaN,21270.0,21299.0,NaN,-28.0,1
5524991,N0091607,1198,3735.0,2709.0,893.0,NaN,55.0,1.0,53.0,NaN,...,-69.0,NaN,130.0,2579.0,NaN,2709.0,2709.0,NaN,NaN,1

In [ ]:
mod_cols = list(set(Pct_100_columns[:-1]) - set(new_delete_cols))
slim_df[slim_df[mod_cols] == 0] = np.nan

In [ ]:
dict_cols = {}
for col in slim_df.columns.to_list():
    notnull_ratio = slim_df.loc[slim_df['上場フラグ'] == 1, col].notnull().sum() / len(slim_df.loc[slim_df['上場フラグ'] == 1])
    print(f'Column: {col}, Not Null Ratio (上場フラグ=1): {notnull_ratio:.4f}')
    dict_cols[col] = notnull_ratio

Column: nikkei, Not Null Ratio (上場フラグ=1): 1.0000
Column: week_id, Not Null Ratio (上場フラグ=1): 1.0000
Column: 流動資産, Not Null Ratio (上場フラグ=1): 0.9987
Column: 現金・預金／現金及び現金同等物, Not Null Ratio (上場フラグ=1): 0.9986
Column: 受取手形・売掛金及び契約資産／売掛金及びその他の短期債権, Not Null Ratio (上場フラグ=1): 0.9528
Column: 有価証券, Not Null Ratio (上場フラグ=1): 0.2785
Column: 棚卸資産, Not Null Ratio (上場フラグ=1): 0.9509
Column: 商品・製品, Not Null Ratio (上場フラグ=1): 0.3998
Column: 半製品・仕掛品, Not Null Ratio (上場フラグ=1): 0.6933
Column: 原材料・貯蔵品, Not Null Ratio (上場フラグ=1): 0.3646
Column: 前渡金, Not Null Ratio (上場フラグ=1): 0.2584
Column: 前払費用, Not Null Ratio (上場フラグ=1): 0.8188
Column: 未収入金, Not Null Ratio (上場フラグ=1): 0.5701
Column: 短期貸付金, Not Null Ratio (上場フラグ=1): 0.3777
Column: 繰延税金資産, Not Null Ratio (上場フラグ=1): 0.8392
Column: その他流動資産／その他の金融資産, Not Null Ratio (上場フラグ=1): 0.9956
Column: 貸倒引当金（▲）, Not Null Ratio (上場フラグ=1): 0.7790
Column: 固定資産／非流動資産, Not Null Ratio (上場フラグ=1): 0.9986
Column: 有形固定資産, Not Null Ratio (上場フラグ=1): 0.9941
Column: 償却対象有形固定資産, Not Null Ratio (上場フラグ=1): 0.9906
Column: 建物・構築物, Not Null Ratio (上場フラグ=1): 0.9247
Column: 機械装置及び運搬具, Not Null Ratio (上場フラグ=1): 0.7076
Column: 工具・器具及び備品, Not Null Ratio (上場フラグ=1): 0.9452
Column: リース資産, Not Null Ratio (上場フラグ=1): 0.1211
Column: その他償却対象有形固定資産, Not Null Ratio (上場フラグ=1): 0.6935
Column: 建設仮勘定, Not Null Ratio (上場フラグ=1): 0.6572
Column: 土地・その他非償却対象有形固定資産, Not Null Ratio (上場フラグ=1): 0.8541
Column: 無形固定資産／無形資産, Not Null Ratio (上場フラグ=1): 0.9845
Column: ソフトウェア, Not Null Ratio (上場フラグ=1): 0.8656
Column: のれん, Not Null Ratio (上場フラグ=1): 0.3665
Column: その他無形固定資産／その他無形資産, Not Null Ratio (上場フラグ=1): 0.8660
Column: 投資・その他の資産合計, Not Null Ratio (上場フラグ=1): 0.9985
Column: 投資有価証券・関係会社株式・出資金, Not Null Ratio (上場フラグ=1): 0.9662
Column: 長期貸付金, Not Null Ratio (上場フラグ=1): 0.6679
Column: 破産債権・更生債権・長期債権, Not Null Ratio (上場フラグ=1): 0.3160
Column: 長期前払費用, Not Null Ratio (上場フラグ=1): 0.5764
Column: 退職給付に係る資産（前払年金費用）, Not Null Ratio (上場フラグ=1): 0.2273
Column: 敷金・差入保証金, Not Null Ratio (上場フラグ=1): 0.5435
Column: その他の投資・その他の資産／その他非流動資産, Not Null Ratio (上場フラグ=1): 0.9703
Column: 資産合計, Not Null Ratio (上場フラグ=1): 0.9995
Column: 流動負債, Not Null Ratio (上場フラグ=1): 0.9987
Column: 支払手形・買掛金／買掛金及びその他の短期債務, Not Null Ratio (上場フラグ=1): 0.9140
Column: 短期借入金・社債合計, Not Null Ratio (上場フラグ=1): 0.8678
Column: １年内返済の借入金, Not Null Ratio (上場フラグ=1): 0.8641
Column: １年内償還の社債・転換社債, Not Null Ratio (上場フラグ=1): 0.2135
Column: リース債務, Not Null Ratio (上場フラグ=1): 0.5677
Column: 未払金・未払費用, Not Null Ratio (上場フラグ=1): 0.9819
Column: 未払法人税等, Not Null Ratio (上場フラグ=1): 0.9880
Column: 未払消費税等, Not Null Ratio (上場フラグ=1): 0.3591
Column: 繰延税金負債, Not Null Ratio (上場フラグ=1): 0.5660
Column: 前受金, Not Null Ratio (上場フラグ=1): 0.5348
Column: 預り金, Not Null Ratio (上場フラグ=1): 0.8182
Column: 前受収益, Not Null Ratio (上場フラグ=1): 0.1529
Column: 賞与引当金, Not Null Ratio (上場フラグ=1): 0.8089
Column: 役員賞与引当金（未払役員報酬・賞与）, Not Null Ratio (上場フラグ=1): 0.2713
Column: その他短期引当金, Not Null Ratio (上場フラグ=1): 0.4777
Column: 設備関係支払手形, Not Null Ratio (上場フラグ=1): 0.1524
Column: その他流動負債／その他の金融負債, Not Null Ratio (上場フラグ=1): 0.9846
Column: 固定負債／非流動負債, Not Null Ratio (上場フラグ=1): 0.9877
Column: 長期借入金・社債・転換社債, Not Null Ratio (上場フラグ=1): 0.7770
Column: 社債・転換社債, Not Null Ratio (上場フラグ=1): 0.2651
Column: 長期借入金, Not Null Ratio (上場フラグ=1): 0.7626
Column: 長期未払金, Not Null Ratio (上場フラグ=1): 0.2112
Column: 引当金合計, Not Null Ratio (上場フラグ=1): 0.8431
Column: 退職給付に係る負債（退職給付引当金）, Not Null Ratio (上場フラグ=1): 0.5803
Column: 再評価に係る繰延税金負債, Not Null Ratio (上場フラグ=1): 0.1041
Column: 資産除去債務／資産除去債務引当金, Not Null Ratio (上場フラグ=1): 0.4204
Column: その他固定負債／その他非流動負債／その他の負債, Not Null Ratio (上場フラグ=1): 0.8924
Column: 負債合計, Not Null Ratio (上場フラグ=1): 0.9992
Column: 純資産合計／資本合計, Not Null Ratio (上場フラグ=1): 0.9225
Column: 株主資本, Not Null Ratio (上場フラグ=1): 0.9217
Column: 資本金, Not Null Ratio (上場フラグ=1): 0.9987
Column: 資本剰余金, Not Null Ratio (上場フラグ=1): 0.9707
Column: 資本準備金, Not Null Ratio (上場フラグ=1): 0.9483
Column: その他資本剰余金, Not Null Ratio (上場フラグ=1): 0.4228
Column: 利益剰余金, Not Null Ratio (上場フラグ=1): 0.9974
Column: 利益準備金, Not Null Ratio (上場フラグ=1): 0.6960
Column: その他利益剰余金, Not Null Ratio (上場フラグ=1): 0.9118
Column: 任意積立金, Not Null Ratio (上場フラグ=1): 0.6562
Column: 繰越利益剰余金, Not Null Ratio (上場フラグ=1): 0.9889
Column: 自己株式（▲）, Not Null Ratio (上場フラグ=1): 0.8521
Column: 評価・換算差額等／累積その他の包括利益, Not Null Ratio (上場フラグ=1): 0.8267
Column: その他有価証券再評価差額金／金融資産の公正価値, Not Null Ratio (上場フラグ=1): 0.8453
Column: 繰延ヘッジ損益／キャッシュフローヘッジ, Not Null Ratio (上場フラグ=1): 0.2255
Column: 土地再評価差額金, Not Null Ratio (上場フラグ=1): 0.1423
Column: 為替換算調整勘定／在外営業活動体の換算差額, Not Null Ratio (上場フラグ=1): 0.5483
Column: 退職給付に係る調整累計額, Not Null Ratio (上場フラグ=1): 0.3429
Column: 新株予約権, Not Null Ratio (上場フラグ=1): 0.2389
Column: 非支配株主持分／非支配持分, Not Null Ratio (上場フラグ=1): 0.5194
Column: 負債・純資産合計／資本及び負債合計, Not Null Ratio (上場フラグ=1): 0.9994
Column: 自己資本／親会社の所有者に帰属する資本, Not Null Ratio (上場フラグ=1): 0.9996
Column: 売上高・営業収益, Not Null Ratio (上場フラグ=1): 0.9795
Column: 営業費用, Not Null Ratio (上場フラグ=1): 0.9686
Column: 売上原価・営業原価, Not Null Ratio (上場フラグ=1): 0.9868
Column: 売上総利益, Not Null Ratio (上場フラグ=1): 0.9889
Column: 販売費及び一般管理費, Not Null Ratio (上場フラグ=1): 0.9998
Column: 営業利益, Not Null Ratio (上場フラグ=1): 0.9999
Column: 営業外収益, Not Null Ratio (上場フラグ=1): 0.9920
Column: 受取利息・配当金, Not Null Ratio (上場フラグ=1): 0.9128
Column: 有価証券売却益, Not Null Ratio (上場フラグ=1): 0.5192
Column: その他資産処分益・評価益, Not Null Ratio (上場フラグ=1): 0.1038
Column: 持分法による投資利益, Not Null Ratio (上場フラグ=1): 0.3059
Column: 賃貸料収入, Not Null Ratio (上場フラグ=1): 0.3815
Column: その他営業外収益, Not Null Ratio (上場フラグ=1): 0.9850
Column: 営業外費用, Not Null Ratio (上場フラグ=1): 0.9886
Column: 支払利息・割引料, Not Null Ratio (上場フラグ=1): 0.2639
Column: 有価証券売却損, Not Null Ratio (上場フラグ=1): 0.1402
Column: 有価証券評価損, Not Null Ratio (上場フラグ=1): 0.5878
Column: その他資産処分損・評価損, Not Null Ratio (上場フラグ=1): 0.1550
Column: 持分法による投資損失, Not Null Ratio (上場フラグ=1): 0.1668
Column: その他営業外費用, Not Null Ratio (上場フラグ=1): 0.9563
Column: 経常利益／税金等調整前当期純利益, Not Null Ratio (上場フラグ=1): 0.9999
Column: 特別利益, Not Null Ratio (上場フラグ=1): 0.8823
Column: 事業・組織再編関連利益, Not Null Ratio (上場フラグ=1): 0.5345
Column: その他特別利益, Not Null Ratio (上場フラグ=1): 0.5458
Column: 特別損失, Not Null Ratio (上場フラグ=1): 0.9548
Column: 減損損失, Not Null Ratio (上場フラグ=1): 0.8291
Column: 減価償却費, Not Null Ratio (上場フラグ=1): 0.9478
Column: 退職給付関連費用, Not Null Ratio (上場フラグ=1): 0.1023
Column: 引当金・準備金繰入額, Not Null Ratio (上場フラグ=1): 0.1445
Column: その他特別損失, Not Null Ratio (上場フラグ=1): 0.6822
Column: 税金等調整前当期純利益, Not Null Ratio (上場フラグ=1): 0.9999
Column: 税金等調整前当期利益, Not Null Ratio (上場フラグ=1): 0.9998
Column: 法人税等, Not Null Ratio (上場フラグ=1): 0.9987
Column: 法人税・住民税及び事業税合計／当期税金費用, Not Null Ratio (上場フラグ=1): 0.9979
Column: 法人税等調整額／繰延税金費用, Not Null Ratio (上場フラグ=1): 0.9755
Column: 当期純利益（連結）, Not Null Ratio (上場フラグ=1): 0.6836
Column: 非支配株主に帰属する当期純利益, Not Null Ratio (上場フラグ=1): 0.5362
Column: 親会社株主に帰属する当期純利益（連結）／当期利益（単独）, Not Null Ratio (上場フラグ=1): 0.9999
Column: 有価証券及び投資有価証券売却損益（▲益）, Not Null Ratio (上場フラグ=1): 0.4008
Column: 有価証券評価損益（▲益）, Not Null Ratio (上場フラグ=1): 0.3263
Column: 固定資産売却損益（▲益）, Not Null Ratio (上場フラグ=1): 0.4935
Column: 固定資産除却損益（▲益）, Not Null Ratio (上場フラグ=1): 0.4118
Column: のれん・負ののれん償却額, Not Null Ratio (上場フラグ=1): 0.3542
Column: 貸倒引当金の増加額（▲減）, Not Null Ratio (上場フラグ=1): 0.6275
Column: 退職給付及び役員退職慰労引当金の増減額（▲減）, Not Null Ratio (上場フラグ=1): 0.7486
Column: 賞与引当金の増加額（▲減）, Not Null Ratio (上場フラグ=1): 0.6311
Column: その他の引当金の増加額（▲減）, Not Null Ratio (上場フラグ=1): 0.4016
Column: 受取利息及び受取配当金（▲）, Not Null Ratio (上場フラグ=1): 0.8216
Column: 支払利息, Not Null Ratio (上場フラグ=1): 0.8131
Column: 為替差損（▲益）, Not Null Ratio (上場フラグ=1): 0.2740
Column: 持分法による投資損益（▲益）, Not Null Ratio (上場フラグ=1): 0.3292
Column: 売上債権の減少額（▲増）, Not Null Ratio (上場フラグ=1): 0.9408
Column: 棚卸資産の減少額（▲増）, Not Null Ratio (上場フラグ=1): 0.8907
Column: 仕入債務の増加額（▲減）, Not Null Ratio (上場フラグ=1): 0.9162
Column: 未払消費税等の増加額（▲減）, Not Null Ratio (上場フラグ=1): 0.4402
Column: その他の流動資産の減少額（▲増）, Not Null Ratio (上場フラグ=1): 0.4783
Column: その他の流動負債の増加額（▲減）, Not Null Ratio (上場フラグ=1): 0.6205
Column: その他の小計欄より上の営業キャッシュフロー, Not Null Ratio (上場フラグ=1): 0.9272
Column: 小計, Not Null Ratio (上場フラグ=1): 0.9533
Column: 利息の支払額（▲）, Not Null Ratio (上場フラグ=1): 0.8054
Column: 法人税等の支払額（▲）, Not Null Ratio (上場フラグ=1): 0.9483
Column: その他の小計欄以降の営業キャッシュフロー, Not Null Ratio (上場フラグ=1): 0.2352
Column: 営業活動によるキャッシュフロー, Not Null Ratio (上場フラグ=1): 0.9548
Column: 日経調整営業キャッシュフロー, Not Null Ratio (上場フラグ=1): 0.9548
Column: 定期預金の預入による支出（▲）, Not Null Ratio (上場フラグ=1): 0.4150
Column: 定期預金の払戻による収入, Not Null Ratio (上場フラグ=1): 0.4083
Column: 固定資産の取得による支出（▲）, Not Null Ratio (上場フラグ=1): 0.9485
Column: 有形固定資産の取得による支出（▲）, Not Null Ratio (上場フラグ=1): 0.8301
Column: 無形固定資産の取得による支出（▲）, Not Null Ratio (上場フラグ=1): 0.6394
Column: 固定資産の売却による収入, Not Null Ratio (上場フラグ=1): 0.6987
Column: 有形固定資産の売却による収入, Not Null Ratio (上場フラグ=1): 0.4649
Column: 有価証券の売却による収入, Not Null Ratio (上場フラグ=1): 0.1301
Column: 投資有価証券の取得による支出（▲）, Not Null Ratio (上場フラグ=1): 0.6318
Column: 投資有価証券の売却による収入, Not Null Ratio (上場フラグ=1): 0.5062
Column: 子会社・関係会社株式取得（▲）, Not Null Ratio (上場フラグ=1): 0.2196
Column: 貸付金の増加による支出（▲）, Not Null Ratio (上場フラグ=1): 0.3306
Column: 貸付金の回収による収入, Not Null Ratio (上場フラグ=1): 0.3898
Column: その他の投資活動によるキャッシュフロー, Not Null Ratio (上場フラグ=1): 0.7807
Column: 投資活動によるキャッシュフロー, Not Null Ratio (上場フラグ=1): 0.9544
Column: 日経調整投資キャッシュフロー, Not Null Ratio (上場フラグ=1): 0.9531
Column: 短期借入金による収入, Not Null Ratio (上場フラグ=1): 0.4985
Column: 短期借入金の返済による支出（▲）, Not Null Ratio (上場フラグ=1): 0.4740
Column: リース債務の返済（▲）, Not Null Ratio (上場フラグ=1): 0.3884
Column: 長期借入金による収入, Not Null Ratio (上場フラグ=1): 0.5355
Column: 長期借入金の返済による支出（▲）, Not Null Ratio (上場フラグ=1): 0.7221
Column: 社債の償還による支出（▲）, Not Null Ratio (上場フラグ=1): 0.1898
Column: 株式の発行による収入, Not Null Ratio (上場フラグ=1): 0.1496
Column: 自己株式の取得による支出（▲）, Not Null Ratio (上場フラグ=1): 0.3601
Column: 自己株式の処分による収入, Not Null Ratio (上場フラグ=1): 0.1006
Column: 配当金の支払金額（▲）, Not Null Ratio (上場フラグ=1): 0.7978
Column: 非支配株主への配当金の支払額（▲）, Not Null Ratio (上場フラグ=1): 0.2577
Column: その他の財務活動によるキャッシュフロー, Not Null Ratio (上場フラグ=1): 0.4543
Column: 財務活動によるキャッシュフロー, Not Null Ratio (上場フラグ=1): 0.9526
Column: 日経調整財務キャッシュフロー, Not Null Ratio (上場フラグ=1): 0.9495
Column: 現金及び現金同等物に関わる換算差額, Not Null Ratio (上場フラグ=1): 0.5795
Column: 現金及び現金同等物の増加額（▲減）, Not Null Ratio (上場フラグ=1): 0.9547
Column: 現金及び現金同等物の期首残高, Not Null Ratio (上場フラグ=1): 0.9546
Column: その他の変更による影響額, Not Null Ratio (上場フラグ=1): 0.1254
Column: 現金及び現金同等物の期末残高, Not Null Ratio (上場フラグ=1): 0.9548
Column: 現金及び預金, Not Null Ratio (上場フラグ=1): 0.9518
Column: 預入期間が３ヵ月を超える定期預金（▲）, Not Null Ratio (上場フラグ=1): 0.6108
Column: その他現金及び現金同等物, Not Null Ratio (上場フラグ=1): 0.1145
Column: 上場フラグ, Not Null Ratio (上場フラグ=1): 1.0000

In [ ]:
subject_name = list(dict_cols.keys())
subject_missing_ratio = list(dict_cols.values())
df_dict = pd.DataFrame({'subject_name': subject_name, 'subject_missing_ratio': subject_missing_ratio})
df_dict = df_dict[df_dict['subject_name'].isin([col for col in slim_df.columns.to_list() if col not in ['上場フラグ', 'nikkei', 'week_id']])]
df_dict

                     subject_name  subject_missing_ratio
2                            流動資産               0.998731
3                 現金・預金／現金及び現金同等物               0.998606
4    受取手形・売掛金及び契約資産／売掛金及びその他の短期債権               0.952807
5                            有価証券               0.278480
6                            棚卸資産               0.950949
..                            ...                    ...
188                  その他の変更による影響額               0.125412
189                現金及び現金同等物の期末残高               0.954799
190                        現金及び預金               0.951818
191           預入期間が３ヵ月を超える定期預金（▲）               0.610816
192                  その他現金及び現金同等物               0.114496

[191 rows x 2 columns]

In [ ]:
df_vif_missing_ratio = pd.merge(df_vif, df_dict, how='inner', left_index=True, right_on='subject_name')
df_vif_missing_ratio.reset_index(drop=False, inplace=True)

In [ ]:
df_vif_missing_ratio.to_csv('./vif_missing_ratio_after_dropping_under10PctCols.csv', index=False)

In [ ]:
df_vif_missing_ratio[df_vif_missing_ratio['VIF'] < 10].to_csv('under_10vif_missing_ratio_after_dropping_under10PctCols.csv', index=False)
df_vif_missing_ratio[df_vif_missing_ratio['VIF'] >= 10].to_csv('over_10vif_missing_ratio_after_dropping_under10PctCols.csv', index=False)
print(f'under_length : {len(df_vif_missing_ratio[df_vif_missing_ratio['VIF'] < 10])}')
print(f' over_length : {len(df_vif_missing_ratio[df_vif_missing_ratio['VIF'] >= 10])}')

under_length : 113
 over_length : 78

In [ ]:
over10col_df = slim_df.loc[:, ['nikkei', 'week_id', '上場フラグ'] + df_vif_missing_ratio[df_vif_missing_ratio['VIF'] >= 10]['subject_name'].to_list()]

In [ ]:
over10col_df

,nikkei,week_id,上場フラグ,再評価に係る繰延税金負債,未払金・未払費用,法人税等,機械装置及び運搬具,長期借入金の返済による支出（▲）,貸付金の回収による収入,為替換算調整勘定／在外営業活動体の換算差額,...,現金及び現金同等物の期首残高,日経調整財務キャッシュフロー,財務活動によるキャッシュフロー,固定資産／非流動資産,負債合計,資産合計,日経調整投資キャッシュフロー,投資活動によるキャッシュフロー,日経調整営業キャッシュフロー,営業活動によるキャッシュフロー
0,N0000001,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,N0000002,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,N0000003,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,N0000004,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,N0000005,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5524987,N0091164,1198,1,NaN,208.0,138.0,651.0,-50.0,NaN,3122.0,...,7061.0,-225.0,-225.0,8519.0,4851.0,24357.0,-529.0,-419.0,1795.0,1685.0
5524988,N0091165,1198,1,NaN,128.0,42.0,205.0,NaN,NaN,NaN,...,3224.0,-480.0,-480.0,5811.0,2539.0,12421.0,-977.0,-977.0,62.0,62.0
5524989,N0091290,1198,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5524990,N0091517,1198,1,NaN,11702.0,3452.0,4.0,-200.0,NaN,1358.0,...,16343.0,-2454.0,-2454.0,57805.0,53567.0,121523.0,-4769.0,-4769.0,11795.0,11795.0
5524991,N0091607,1198,1,NaN,259.0,68.0,NaN,NaN,NaN,NaN,...,2579.0,-69.0,-69.0,724.0,1505.0,4459.0,-13.0,-13.0,214.0,214.0

In [ ]:
x = over10col_df.drop(columns=['nikkei', 'week_id', '上場フラグ'])
x.fillna(0, inplace=True)
vif = np.diag(np.linalg.inv(x.corr().values))
df_vif = pd.DataFrame(vif)
df_vif.columns = ["VIF"]
df_vif.index = x.corr().columns
df_vif.sort_values("VIF")

                            VIF
長期借入金の返済による支出（▲）       5.577648
固定資産の売却による収入           5.657206
法人税等                   6.146575
機械装置及び運搬具              6.183194
未払金・未払費用               6.395078
...                         ...
資産合計               46895.664604
日経調整投資キャッシュフロー     84621.903346
投資活動によるキャッシュフロー    84668.598195
日経調整営業キャッシュフロー    107100.308898
営業活動によるキャッシュフロー   107162.415548

[78 rows x 1 columns]

In [ ]:
df_vif.to_csv('./vif_over10col_after_dropping_under10PctCols.csv', index=True)

In [ ]:
slim_df.to_csv('../data/main/master/product/slim_weekly_FR.csv', index=False)

## ラベルをさらに縮小する

In [ ]:
slim_df = pd.read_csv('../data/main/master/product/slim_weekly_FR.csv')

In [ ]:
origin_slim_df = slim_df.copy()

In [ ]:
cols = [
    '流動資産',
    '固定資産／非流動資産',
    '資産合計',
    '流動負債',
    '長期借入金',
    '資本金',
    '資本剰余金',
    '利益剰余金',
    '自己資本／親会社の所有者に帰属する資本',
    '売上総利益',
    '売上高・営業収益',
    '営業利益',
    '経常利益／税金等調整前当期純利益',
    '減価償却費',
    '法人税等',
    '営業活動によるキャッシュフロー',
    '投資活動によるキャッシュフロー',
    '現金及び現金同等物の期首残高',
    '現金及び現金同等物の期末残高',
    '現金及び預金',
]

def impute_critical_missing(df:pd.DataFrame, col:list[str]) -> pd.DataFrame:
    df = df.sort_values('week_id')
    for col in cols:
        df[col] = df[col].interpolate(method='linear', limit_direction='both')
    return df

origin_slim_df = (
    origin_slim_df
    .groupby('nikkei')
    .apply(lambda group: impute_critical_missing(df=group, col=cols))
    ).reset_index(drop=True)

C:\Users\Ito Yuki\AppData\Local\Temp\ipykernel_15680\1950603673.py:33: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  .apply(lambda group: impute_critical_missing(df=group, col=cols))

In [ ]:
origin_slim_df.loc[origin_slim_df['株主資本'].isna() & origin_slim_df['上場フラグ'] == 1, '株主資本'] = (
    origin_slim_df['資本金'].fillna(0) +
    origin_slim_df['資本剰余金'].fillna(0) +
    origin_slim_df['利益剰余金'].fillna(0)
)

origin_slim_df.loc[origin_slim_df['株主資本'] == 0, '株主資本'] = np.nan
origin_slim_df.drop(columns=['資本金', '資本剰余金', '利益剰余金'], inplace=True)
print(f'Exit Ratio : {origin_slim_df.loc[origin_slim_df['上場フラグ'] == 1, '株主資本'].notnull().sum() / len(origin_slim_df.loc[origin_slim_df['上場フラグ'] == 1, '株主資本'])}')

Exit Ratio : 1.0

In [ ]:
origin_slim_df.loc[origin_slim_df['税金等調整前当期純利益'].isna() & origin_slim_df['上場フラグ'] == 1, '税金等調整前当期純利益'] = (
    origin_slim_df['経常利益／税金等調整前当期純利益'].fillna(0) +
    origin_slim_df['特別利益'].fillna(0) -
    origin_slim_df['特別損失'].fillna(0)
)

origin_slim_df.loc[origin_slim_df['税金等調整前当期純利益'] == 0, '税金等調整前当期純利益'] = np.nan
print(f'Exit Ratio : {origin_slim_df.loc[origin_slim_df['上場フラグ'] == 1, '税金等調整前当期純利益'].notnull().sum() / len(origin_slim_df.loc[origin_slim_df['上場フラグ'] == 1, '税金等調整前当期純利益'])}')

Exit Ratio : 0.9657351881559192

In [ ]:
origin_slim_df['当期純利益'] = origin_slim_df['当期純利益（連結）']
origin_slim_df.drop(columns=['当期純利益（連結）'], inplace=True)
origin_slim_df.loc[origin_slim_df['当期純利益'].isna() & origin_slim_df['上場フラグ'] == 1, '当期純利益'] = (
    origin_slim_df['税金等調整前当期純利益'] -
    origin_slim_df['法人税等'].fillna(0)
)

origin_slim_df.loc[origin_slim_df['当期純利益'] == 0, '当期純利益'] = np.nan
print(f'Exit Ratio : {origin_slim_df.loc[origin_slim_df['上場フラグ'] == 1, '当期純利益'].notnull().sum() / len(origin_slim_df.loc[origin_slim_df['上場フラグ'] == 1, '当期純利益'])}')

Exit Ratio : 0.962065059216551

In [ ]:
origin_slim_df['フリーキャッシュフロー'] = (
    origin_slim_df['営業活動によるキャッシュフロー'].fillna(0) +
    origin_slim_df['投資活動によるキャッシュフロー'].fillna(0)
)
origin_slim_df.loc[origin_slim_df['フリーキャッシュフロー'] == 0, 'フリーキャッシュフロー'] = np.nan
print(f'Exit Ratio : {origin_slim_df.loc[origin_slim_df['上場フラグ'] == 1, 'フリーキャッシュフロー'].notnull().sum() / len(origin_slim_df.loc[origin_slim_df['上場フラグ'] == 1, 'フリーキャッシュフロー'])}')

Exit Ratio : 0.9985390125394467

In [ ]:
origin_slim_df['ギアリング比率'] = (
    origin_slim_df['負債合計'] / 
    origin_slim_df['自己資本／親会社の所有者に帰属する資本']
)
origin_slim_df.loc[origin_slim_df['ギアリング比率'] == 0, 'ギアリング比率'] = np.nan
print(f'Exit Ratio : {origin_slim_df.loc[origin_slim_df['上場フラグ'] == 1, 'ギアリング比率'].notnull().sum() / len(origin_slim_df.loc[origin_slim_df['上場フラグ'] == 1, 'ギアリング比率'])}')

Exit Ratio : 0.9992178097903499

In [ ]:
origin_slim_df['総資産回転率'] = (
    origin_slim_df['売上高・営業収益'] /
    origin_slim_df['資産合計']
)
origin_slim_df.loc[origin_slim_df['総資産回転率'] == 0, '総資産回転率'] = np.nan
print(f'Exit Ratio : {origin_slim_df.loc[origin_slim_df['上場フラグ'] == 1, '総資産回転率'].notnull().sum() / len(origin_slim_df.loc[origin_slim_df['上場フラグ'] == 1, '総資産回転率'])}')

Exit Ratio : 0.9999678903854824

In [ ]:
origin_slim_df['固定比率'] = (
    origin_slim_df['固定資産／非流動資産'] /
    origin_slim_df['資産合計']
)

origin_slim_df.loc[origin_slim_df['固定比率'] == 0, '固定比率'] = np.nan
print(f'Exit Ratio : {origin_slim_df.loc[origin_slim_df['上場フラグ'] == 1, '固定比率'].notnull().sum() / len(origin_slim_df.loc[origin_slim_df['上場フラグ'] == 1, '固定比率'])}')

Exit Ratio : 1.0

In [ ]:
origin_slim_df['流動比率'] = (
    origin_slim_df['流動資産'] /
    origin_slim_df['流動負債']
)
origin_slim_df.loc[origin_slim_df['流動比率'] == 0, '流動比率'] = np.nan
print(f'Exit Ratio : {origin_slim_df.loc[origin_slim_df['上場フラグ'] == 1, '流動比率'].notnull().sum() / len(origin_slim_df.loc[origin_slim_df['上場フラグ'] == 1, '流動比率'])}')

Exit Ratio : 1.0

In [ ]:
origin_slim_df['自己資本比率'] = (
    origin_slim_df['自己資本／親会社の所有者に帰属する資本'] /
    origin_slim_df['資産合計']
)
origin_slim_df.loc[origin_slim_df['自己資本比率'] == 0, '自己資本比率'] = np.nan
print(f'Exit Ratio : {origin_slim_df.loc[origin_slim_df['上場フラグ'] == 1, '自己資本比率'].notnull().sum() / len(origin_slim_df.loc[origin_slim_df['上場フラグ'] == 1, '自己資本比率'])}')

Exit Ratio : 0.9999935780770964

In [ ]:
origin_slim_df['売上高総利益率'] = (
    origin_slim_df['売上総利益'] /
    origin_slim_df['売上高・営業収益']
)

origin_slim_df.loc[origin_slim_df['売上高総利益率'] == 0, '売上高総利益率'] = np.nan
print(f'Exit Ratio : {origin_slim_df.loc[origin_slim_df['上場フラグ'] == 1, '売上高総利益率'].notnull().sum() / len(origin_slim_df.loc[origin_slim_df['上場フラグ'] == 1, '売上高総利益率'])}')

Exit Ratio : 0.9788211404564446

In [ ]:
origin_slim_df['売上高営業利益率'] = (
    origin_slim_df['売上総利益'] /
    origin_slim_df['売上高・営業収益']
)

origin_slim_df.loc[origin_slim_df['売上高営業利益率'] == 0, '売上高営業利益率'] = np.nan
print(f'Exit Ratio : {origin_slim_df.loc[origin_slim_df['上場フラグ'] == 1, '売上高営業利益率'].notnull().sum() / len(origin_slim_df.loc[origin_slim_df['上場フラグ'] == 1, '売上高営業利益率'])}')

Exit Ratio : 0.9788211404564446

In [ ]:
origin_slim_df['売上高経常利益率'] = (
    origin_slim_df['売上総利益'] /
    origin_slim_df['経常利益／税金等調整前当期純利益']
)

origin_slim_df.loc[origin_slim_df['売上高経常利益率'] == 0, '売上高経常利益率'] = np.nan
print(f'Exit Ratio : {origin_slim_df.loc[origin_slim_df['上場フラグ'] == 1, '売上高経常利益率'].notnull().sum() / len(origin_slim_df.loc[origin_slim_df['上場フラグ'] == 1, '売上高経常利益率'])}')

Exit Ratio : 0.9788211404564446

In [ ]:
origin_slim_df['有利子負債'] = (
    origin_slim_df['短期借入金・社債合計'].fillna(0) +
    origin_slim_df['１年内返済の借入金'].fillna(0) +
    origin_slim_df['社債・転換社債'].fillna(0) +
    origin_slim_df['長期借入金'].fillna(0)
)

origin_slim_df.loc[origin_slim_df['売上高経常利益率'] == 0, '売上高経常利益率'] = np.nan
print(f'Exit Ratio : {origin_slim_df.loc[origin_slim_df['上場フラグ'] == 1, '売上高経常利益率'].notnull().sum() / len(origin_slim_df.loc[origin_slim_df['上場フラグ'] == 1, '売上高経常利益率'])}')

Exit Ratio : 0.9788211404564446

In [ ]:
origin_slim_df['流動資産率'] = (
    origin_slim_df['流動資産'] /
    origin_slim_df['資産合計']
)

origin_slim_df.loc[origin_slim_df['流動資産率'] == 0, '流動資産率'] = np.nan
print(f'Exit Ratio : {origin_slim_df.loc[origin_slim_df['上場フラグ'] == 1, '流動資産率'].notnull().sum() / len(origin_slim_df.loc[origin_slim_df['上場フラグ'] == 1, '流動資産率'])}')

Exit Ratio : 1.0

In [ ]:
origin_slim_df['固定資産率'] = (
    origin_slim_df['固定資産／非流動資産'] /
    origin_slim_df['資産合計']
)

origin_slim_df.loc[origin_slim_df['固定資産率'] == 0, '固定資産率'] = np.nan
print(f'Exit Ratio : {origin_slim_df.loc[origin_slim_df['上場フラグ'] == 1, '固定資産率'].notnull().sum() / len(origin_slim_df.loc[origin_slim_df['上場フラグ'] == 1, '固定資産率'])}')

Exit Ratio : 1.0

In [ ]:
origin_slim_df.loc[origin_slim_df['現金及び現金同等物の増加額（▲減）'].isna() & origin_slim_df['上場フラグ'] == 1, '現金及び現金同等物の増加額（▲減）'] = (
    origin_slim_df['現金及び現金同等物の期末残高'].fillna(0) -
    origin_slim_df['現金及び現金同等物の期首残高'].fillna(0)
)

origin_slim_df.loc[origin_slim_df['現金及び現金同等物の増加額（▲減）'] == 0, '現金及び現金同等物の増加額（▲減）'] = np.nan
print(f'Exit Ratio : {origin_slim_df.loc[origin_slim_df['上場フラグ'] == 1, '現金及び現金同等物の増加額（▲減）'].notnull().sum() / len(origin_slim_df.loc[origin_slim_df['上場フラグ'] == 1, '現金及び現金同等物の増加額（▲減）'])}')

Exit Ratio : 0.9989012089912058

In [ ]:
origin_slim_df['EBITDA'] = (
    origin_slim_df['営業利益'].fillna(0) +
    origin_slim_df['減価償却費'].fillna(0)
)
origin_slim_df.loc[origin_slim_df['EBITDA'] == 0, 'EBITDA'] = np.nan
print(f'Exit Ratio : {origin_slim_df.loc[origin_slim_df['上場フラグ'] == 1, 'EBITDA'].notnull().sum() / len(origin_slim_df.loc[origin_slim_df['上場フラグ'] == 1, 'EBITDA'])}')

Exit Ratio : 0.9991413889077979

In [ ]:
origin_slim_df['ROE'] = (
    origin_slim_df['当期純利益'] /
    origin_slim_df['自己資本／親会社の所有者に帰属する資本']
)

origin_slim_df.loc[origin_slim_df['ROE'] == 0, 'ROE'] = np.nan
print(f'Exit Ratio : {origin_slim_df.loc[origin_slim_df['上場フラグ'] == 1, 'ROE'].notnull().sum() / len(origin_slim_df.loc[origin_slim_df['上場フラグ'] == 1, 'ROE'])}')

Exit Ratio : 0.962065059216551

In [ ]:
origin_slim_df['ROA'] = (
    origin_slim_df['当期純利益'] /
    origin_slim_df['資産合計']
)

origin_slim_df.loc[origin_slim_df['ROA'] == 0, 'ROA'] = np.nan
print(f'Exit Ratio : {origin_slim_df.loc[origin_slim_df['上場フラグ'] == 1, 'ROA'].notnull().sum() / len(origin_slim_df.loc[origin_slim_df['上場フラグ'] == 1, 'ROA'])}')

Exit Ratio : 0.962065059216551

In [ ]:
origin_slim_df['株主資本回転率'] = (
    origin_slim_df['売上高・営業収益'] /
    origin_slim_df['株主資本']
)

origin_slim_df.loc[origin_slim_df['株主資本回転率'] == 0, '株主資本回転率'] = np.nan
print(f'Exit Ratio : {origin_slim_df.loc[origin_slim_df['上場フラグ'] == 1, '株主資本回転率'].notnull().sum() / len(origin_slim_df.loc[origin_slim_df['上場フラグ'] == 1, '株主資本回転率'])}')

Exit Ratio : 0.9999678903854824

In [ ]:
def group_function(df:pd.DataFrame, nikkei:str, cols2:str) -> pd.DataFrame:
    for col in cols2:
        print('\r', f'Processing nikkei: {nikkei}, column: {col}', end='               ')
        df[f'{col}の増加額'] = (
            df[col] - df[col].shift(1)
        )

        df.loc[df[f'{col}の増加額'] == 0, f'{col}の増加額'] = np.nan
        # print(f'Exit Ratio : {df.loc[df['上場フラグ'] == 1, f'{col}の増加額'].notnull().sum() / len(df.loc[df['上場フラグ'] == 1, f'{col}の増加額'])}')

In [ ]:
origin_slim_df_grouped = (
    origin_slim_df
    .groupby('nikkei')
    .apply
    (
        lambda group: group_function(df=group, nikkei=group.name, cols2=['売上総利益', '営業利益', '経常利益／税金等調整前当期純利益', '売上高・営業収益'])
    )
    .reset_index(drop=True))

 Processing nikkei: N0091607, column: 売上高・営業収益

C:\Users\Ito Yuki\AppData\Local\Temp\ipykernel_15680\376085982.py:4: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  .apply

In [ ]:
origin_slim_df.head()

,nikkei,week_id,流動資産,現金・預金／現金及び現金同等物,受取手形・売掛金及び契約資産／売掛金及びその他の短期債権,有価証券,棚卸資産,商品・製品,半製品・仕掛品,原材料・貯蔵品,...,売上高営業利益率,売上高経常利益率,有利子負債,流動資産率,固定資産率,EBITDA,ROE,ROA,株主資本回転率,自己資本比率
0,N0000001,0,45514.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.09533,7.051693,4552.0,0.751068,0.248766,1911.0,NaN,NaN,NaN,0.18393
1,N0000001,1,45514.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.09533,7.051693,4552.0,0.751068,0.248766,1911.0,NaN,NaN,NaN,0.18393
2,N0000001,2,45514.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.09533,7.051693,4552.0,0.751068,0.248766,1911.0,NaN,NaN,NaN,0.18393
3,N0000001,3,45514.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.09533,7.051693,4552.0,0.751068,0.248766,1911.0,NaN,NaN,NaN,0.18393
4,N0000001,4,45514.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.09533,7.051693,4552.0,0.751068,0.248766,1911.0,NaN,NaN,NaN,0.18393

In [ ]:
origin_slim_df.to_csv('../data/main/master/product/slim_weekly_FR_before_dropping.csv', index=False)

In [ ]:
origin_slim_df_cols = origin_slim_df.columns.tolist()
for i, col in enumerate(origin_slim_df_cols):
    print(f'Index: {i}, Column: {col}')

Index: 0, Column: nikkei
Index: 1, Column: week_id
Index: 2, Column: 流動資産
Index: 3, Column: 現金・預金／現金及び現金同等物
Index: 4, Column: 受取手形・売掛金及び契約資産／売掛金及びその他の短期債権
Index: 5, Column: 有価証券
Index: 6, Column: 棚卸資産
Index: 7, Column: 商品・製品
Index: 8, Column: 半製品・仕掛品
Index: 9, Column: 原材料・貯蔵品
Index: 10, Column: 前渡金
Index: 11, Column: 前払費用
Index: 12, Column: 未収入金
Index: 13, Column: 短期貸付金
Index: 14, Column: 繰延税金資産
Index: 15, Column: その他流動資産／その他の金融資産
Index: 16, Column: 貸倒引当金（▲）
Index: 17, Column: 固定資産／非流動資産
Index: 18, Column: 有形固定資産
Index: 19, Column: 償却対象有形固定資産
Index: 20, Column: 建物・構築物
Index: 21, Column: 機械装置及び運搬具
Index: 22, Column: 工具・器具及び備品
Index: 23, Column: リース資産
Index: 24, Column: その他償却対象有形固定資産
Index: 25, Column: 建設仮勘定
Index: 26, Column: 土地・その他非償却対象有形固定資産
Index: 27, Column: 無形固定資産／無形資産
Index: 28, Column: ソフトウェア
Index: 29, Column: のれん
Index: 30, Column: その他無形固定資産／その他無形資産
Index: 31, Column: 投資・その他の資産合計
Index: 32, Column: 投資有価証券・関係会社株式・出資金
Index: 33, Column: 長期貸付金
Index: 34, Column: 破産債権・更生債権・長期債権
Index: 35, Column: 長期前払費用
Index: 36, Column: 退職給付に係る資産（前払年金費用）
Index: 37, Column: 敷金・差入保証金
Index: 38, Column: その他の投資・その他の資産／その他非流動資産
Index: 39, Column: 資産合計
Index: 40, Column: 流動負債
Index: 41, Column: 支払手形・買掛金／買掛金及びその他の短期債務
Index: 42, Column: 短期借入金・社債合計
Index: 43, Column: １年内返済の借入金
Index: 44, Column: １年内償還の社債・転換社債
Index: 45, Column: リース債務
Index: 46, Column: 未払金・未払費用
Index: 47, Column: 未払法人税等
Index: 48, Column: 未払消費税等
Index: 49, Column: 繰延税金負債
Index: 50, Column: 前受金
Index: 51, Column: 預り金
Index: 52, Column: 前受収益
Index: 53, Column: 賞与引当金
Index: 54, Column: 役員賞与引当金（未払役員報酬・賞与）
Index: 55, Column: その他短期引当金
Index: 56, Column: 設備関係支払手形
Index: 57, Column: その他流動負債／その他の金融負債
Index: 58, Column: 固定負債／非流動負債
Index: 59, Column: 長期借入金・社債・転換社債
Index: 60, Column: 社債・転換社債
Index: 61, Column: 長期借入金
Index: 62, Column: 長期未払金
Index: 63, Column: 引当金合計
Index: 64, Column: 退職給付に係る負債（退職給付引当金）
Index: 65, Column: 再評価に係る繰延税金負債
Index: 66, Column: 資産除去債務／資産除去債務引当金
Index: 67, Column: その他固定負債／その他非流動負債／その他の負債
Index: 68, Column: 負債合計
Index: 69, Column: 純資産合計／資本合計
Index: 70, Column: 株主資本
Index: 71, Column: 資本準備金
Index: 72, Column: その他資本剰余金
Index: 73, Column: 利益準備金
Index: 74, Column: その他利益剰余金
Index: 75, Column: 任意積立金
Index: 76, Column: 繰越利益剰余金
Index: 77, Column: 自己株式（▲）
Index: 78, Column: 評価・換算差額等／累積その他の包括利益
Index: 79, Column: その他有価証券再評価差額金／金融資産の公正価値
Index: 80, Column: 繰延ヘッジ損益／キャッシュフローヘッジ
Index: 81, Column: 土地再評価差額金
Index: 82, Column: 為替換算調整勘定／在外営業活動体の換算差額
Index: 83, Column: 退職給付に係る調整累計額
Index: 84, Column: 新株予約権
Index: 85, Column: 非支配株主持分／非支配持分
Index: 86, Column: 負債・純資産合計／資本及び負債合計
Index: 87, Column: 自己資本／親会社の所有者に帰属する資本
Index: 88, Column: 売上高・営業収益
Index: 89, Column: 営業費用
Index: 90, Column: 売上原価・営業原価
Index: 91, Column: 売上総利益
Index: 92, Column: 販売費及び一般管理費
Index: 93, Column: 営業利益
Index: 94, Column: 営業外収益
Index: 95, Column: 受取利息・配当金
Index: 96, Column: 有価証券売却益
Index: 97, Column: その他資産処分益・評価益
Index: 98, Column: 持分法による投資利益
Index: 99, Column: 賃貸料収入
Index: 100, Column: その他営業外収益
Index: 101, Column: 営業外費用
Index: 102, Column: 支払利息・割引料
Index: 103, Column: 有価証券売却損
Index: 104, Column: 有価証券評価損
Index: 105, Column: その他資産処分損・評価損
Index: 106, Column: 持分法による投資損失
Index: 107, Column: その他営業外費用
Index: 108, Column: 経常利益／税金等調整前当期純利益
Index: 109, Column: 特別利益
Index: 110, Column: 事業・組織再編関連利益
Index: 111, Column: その他特別利益
Index: 112, Column: 特別損失
Index: 113, Column: 減損損失
Index: 114, Column: 減価償却費
Index: 115, Column: 退職給付関連費用
Index: 116, Column: 引当金・準備金繰入額
Index: 117, Column: その他特別損失
Index: 118, Column: 税金等調整前当期純利益
Index: 119, Column: 税金等調整前当期利益
Index: 120, Column: 法人税等
Index: 121, Column: 法人税・住民税及び事業税合計／当期税金費用
Index: 122, Column: 法人税等調整額／繰延税金費用
Index: 123, Column: 非支配株主に帰属する当期純利益
Index: 124, Column: 親会社株主に帰属する当期純利益（連結）／当期利益（単独）
Index: 125, Column: 有価証券及び投資有価証券売却損益（▲益）
Index: 126, Column: 有価証券評価損益（▲益）
Index: 127, Column: 固定資産売却損益（▲益）
Index: 128, Column: 固定資産除却損益（▲益）
Index: 129, Column: のれん・負ののれん償却額
Index: 130, Column: 貸倒引当金の増加額（▲減）
Index: 131, Column: 退職給付及び役員退職慰労引当金の増減額（▲減）
Index: 132, Column: 賞与引当金の増加額（▲減）
Index: 133, Column: その他の引当金の増加額（▲減）
Index: 134, Column: 受取利息及び受取配当金（▲）
Index: 135, Column: 支払利息
Index: 136, Column: 為替差損（▲益）
Index: 137, Column: 持分法による投資損益（▲益）
Index: 138, Column: 売上債権の減少額（▲増）
Index: 139, Column: 棚卸資産の減少額（▲増）
Index: 140, Column: 仕入債務の増加額（▲減）
Index: 141, Column: 未払消費税等の増加額（▲減）
Index: 142, Column: その他の流動資産の減少額（▲増）
Index: 143, Column: その他の流動負債の増加額（▲減）
Index: 144, Column: その他の小計欄より上の営業キャッシュフロー
Index: 145, Column: 小計
Index: 146, Column: 利息の支払額（▲）
Index: 147, Column: 法人税等の支払額（▲）
Index: 148, Column: その他の小計欄以降の営業キャッシュフロー
Index: 149, Column: 営業活動によるキャッシュフロー
Index: 150, Column: 日経調整営業キャッシュフロー
Index: 151, Column: 定期預金の預入による支出（▲）
Index: 152, Column: 定期預金の払戻による収入
Index: 153, Column: 固定資産の取得による支出（▲）
Index: 154, Column: 有形固定資産の取得による支出（▲）
Index: 155, Column: 無形固定資産の取得による支出（▲）
Index: 156, Column: 固定資産の売却による収入
Index: 157, Column: 有形固定資産の売却による収入
Index: 158, Column: 有価証券の売却による収入
Index: 159, Column: 投資有価証券の取得による支出（▲）
Index: 160, Column: 投資有価証券の売却による収入
Index: 161, Column: 子会社・関係会社株式取得（▲）
Index: 162, Column: 貸付金の増加による支出（▲）
Index: 163, Column: 貸付金の回収による収入
Index: 164, Column: その他の投資活動によるキャッシュフロー
Index: 165, Column: 投資活動によるキャッシュフロー
Index: 166, Column: 日経調整投資キャッシュフロー
Index: 167, Column: 短期借入金による収入
Index: 168, Column: 短期借入金の返済による支出（▲）
Index: 169, Column: リース債務の返済（▲）
Index: 170, Column: 長期借入金による収入
Index: 171, Column: 長期借入金の返済による支出（▲）
Index: 172, Column: 社債の償還による支出（▲）
Index: 173, Column: 株式の発行による収入
Index: 174, Column: 自己株式の取得による支出（▲）
Index: 175, Column: 自己株式の処分による収入
Index: 176, Column: 配当金の支払金額（▲）
Index: 177, Column: 非支配株主への配当金の支払額（▲）
Index: 178, Column: その他の財務活動によるキャッシュフロー
Index: 179, Column: 財務活動によるキャッシュフロー
Index: 180, Column: 日経調整財務キャッシュフロー
Index: 181, Column: 現金及び現金同等物に関わる換算差額
Index: 182, Column: 現金及び現金同等物の増加額（▲減）
Index: 183, Column: 現金及び現金同等物の期首残高
Index: 184, Column: その他の変更による影響額
Index: 185, Column: 現金及び現金同等物の期末残高
Index: 186, Column: 現金及び預金
Index: 187, Column: 預入期間が３ヵ月を超える定期預金（▲）
Index: 188, Column: その他現金及び現金同等物
Index: 189, Column: 上場フラグ
Index: 190, Column: 当期純利益
Index: 191, Column: フリーキャッシュフロー
Index: 192, Column: ギアリング比率
Index: 193, Column: 総資産回転率
Index: 194, Column: 固定比率
Index: 195, Column: 流動比率
Index: 196, Column: 売上高総利益率
Index: 197, Column: 売上高営業利益率
Index: 198, Column: 売上高経常利益率
Index: 199, Column: 有利子負債
Index: 200, Column: 流動資産率
Index: 201, Column: 固定資産率
Index: 202, Column: EBITDA
Index: 203, Column: ROE
Index: 204, Column: ROA
Index: 205, Column: 株主資本回転率
Index: 206, Column: 自己資本比率

In [ ]:
tmp_df = origin_slim_df.copy()
tmp_df.loc[tmp_df['上場フラグ'] == 0, '当期純利益':] = np.nan

In [ ]:
tmp_df

,nikkei,week_id,流動資産,現金・預金／現金及び現金同等物,受取手形・売掛金及び契約資産／売掛金及びその他の短期債権,有価証券,棚卸資産,商品・製品,半製品・仕掛品,原材料・貯蔵品,...,売上高営業利益率,売上高経常利益率,有利子負債,流動資産率,固定資産率,EBITDA,ROE,ROA,株主資本回転率,自己資本比率
0,N0000001,0,45514.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,N0000001,1,45514.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,N0000001,2,45514.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,N0000001,3,45514.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,N0000001,4,45514.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5524987,N0091607,1194,3735.0,2709.0,893.0,NaN,55.0,1.0,53.0,NaN,...,0.247714,3.995392,375.0,0.837632,0.162368,223.0,0.050102,0.033191,1.235004,0.66248
5524988,N0091607,1195,3735.0,2709.0,893.0,NaN,55.0,1.0,53.0,NaN,...,0.247714,3.995392,375.0,0.837632,0.162368,223.0,0.050102,0.033191,1.235004,0.66248
5524989,N0091607,1196,3735.0,2709.0,893.0,NaN,55.0,1.0,53.0,NaN,...,0.247714,3.995392,375.0,0.837632,0.162368,223.0,0.050102,0.033191,1.235004,0.66248
5524990,N0091607,1197,3735.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5524991,N0091607,1198,3735.0,2709.0,893.0,NaN,55.0,1.0,53.0,NaN,...,0.247714,3.995392,375.0,0.837632,0.162368,223.0,0.050102,0.033191,1.235004,0.66248

In [ ]:
tmp_df.to_csv('../data/main/master/product/slim_weekly_FR_before_dropping.csv', index=False)