## 特徴選択候補

In [1]:
import pandas as pd
import numpy as np
from pathlib import Path

In [2]:
csv_dir = Path('../../data/main/master/product/weekly_remodify_fundamental')
df_list = [pd.read_csv(fp) for fp in csv_dir.rglob('.') if fp.suffix == '.csv']
weekly_FR_df = pd.concat(df_list).reset_index(drop=True)

In [3]:
weekly_FR_df.drop(columns=['jp'], inplace=True)

In [4]:
weekly_FR_df

,nikkei,ticker,流動資産,売却目的保有資産,現金・預金／現金及び現金同等物,受取手形・売掛金及び契約資産／売掛金及びその他の短期債権,非連結子会社関連会社 受取手形・売掛金,リース債権及びリース投資資産,営業貸付金・営業投資有価証券,有価証券,...,現金及び現金同等物の期首残高,その他の変更による影響額,現金及び現金同等物の期末残高,現金及び預金,預入期間が３ヵ月を超える定期預金（▲）,コマーシャルペーパー,譲渡性預金,売り戻し条件付き現先,公社債投信,その他現金及び現金同等物
0,N0000001,1301,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,N0000002,1334,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,N0000003,1332,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,N0000004,1333,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,N0000005,1351,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5524987,N0091164,7841,10616.0,NaN,7110.0,1069.0,NaN,NaN,NaN,NaN,...,5954.0,NaN,6786.0,7110.0,-324.0,NaN,NaN,NaN,NaN,NaN
5524988,N0091165,4923,6892.0,NaN,4437.0,1288.0,NaN,NaN,NaN,50.0,...,1992.0,NaN,2097.5,3766.0,-2000.0,NaN,NaN,NaN,NaN,NaN
5524989,N0091290,4692,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5524990,N0091517,2685,55538.0,NaN,15698.0,6634.0,NaN,NaN,NaN,NaN,...,18647.0,NaN,23976.0,21649.0,NaN,NaN,NaN,NaN,NaN,NaN
5524991,N0091607,4491,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [5]:
corr = weekly_FR_df.iloc[:, 2:].corr()
corr

,流動資産,売却目的保有資産,現金・預金／現金及び現金同等物,受取手形・売掛金及び契約資産／売掛金及びその他の短期債権,非連結子会社関連会社 受取手形・売掛金,リース債権及びリース投資資産,営業貸付金・営業投資有価証券,有価証券,棚卸資産,商品・製品,...,現金及び現金同等物の期首残高,その他の変更による影響額,現金及び現金同等物の期末残高,現金及び預金,預入期間が３ヵ月を超える定期預金（▲）,コマーシャルペーパー,譲渡性預金,売り戻し条件付き現先,公社債投信,その他現金及び現金同等物
流動資産,1.000000,NaN,0.087329,0.678320,0.852119,0.482098,0.226409,0.542449,0.677777,0.577955,...,0.085667,0.171734,0.082722,0.076279,-0.272228,0.364493,0.113077,-0.307153,-0.336317,0.390124
売却目的保有資産,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
現金・預金／現金及び現金同等物,0.087329,NaN,1.000000,0.385585,0.558988,0.198102,0.838461,0.031566,0.047320,0.548275,...,0.989537,0.026318,0.998693,0.998996,-0.039271,0.277394,-0.257717,-0.310229,-0.420244,0.012284
受取手形・売掛金及び契約資産／売掛金及びその他の短期債権,0.678320,NaN,0.385585,1.000000,0.778614,0.161491,0.282244,0.328938,0.344941,0.591655,...,0.348512,0.105189,0.347182,0.350051,-0.108842,0.205744,0.259378,-0.278265,-0.108199,0.182937
非連結子会社関連会社 受取手形・売掛金,0.852119,NaN,0.558988,0.778614,1.000000,NaN,NaN,-0.351443,0.904305,0.882799,...,0.676513,1.000000,0.508463,0.558988,-0.750804,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
コマーシャルペーパー,0.364493,NaN,0.277394,0.205744,NaN,0.170535,0.504771,0.505665,0.179817,0.181100,...,0.443572,0.150080,0.465050,0.276334,-0.119695,1.000000,0.268105,NaN,0.345448,0.309665
譲渡性預金,0.113077,NaN,-0.257717,0.259378,NaN,0.018207,-0.721811,0.189786,0.186825,0.244896,...,-0.189859,-0.005021,-0.252005,-0.257575,-0.123781,0.268105,1.000000,NaN,0.195997,-0.168598
売り戻し条件付き現先,-0.307153,NaN,-0.310229,-0.278265,NaN,NaN,NaN,-0.390728,-0.357908,-0.266891,...,-0.210675,-0.981984,0.074502,-0.310229,0.188376,NaN,NaN,1.000000,-1.000000,0.998103
公社債投信,-0.336317,NaN,-0.420244,-0.108199,NaN,-0.719313,0.053740,-0.503640,-0.241835,0.111729,...,-0.455833,0.034843,-0.448966,-0.425172,0.221549,0.345448,0.195997,-1.000000,1.000000,-0.708305
その他現金及び現金同等物,0.390124,NaN,0.012284,0.182937,NaN,0.009470,-0.247856,0.745978,0.275917,0.143016,...,0.043106,0.010697,0.042298,0.012245,-0.422792,0.309665,-0.168598,0.998103,-0.708305,1.000000

In [6]:
# 相関行列 corr から三角行列を除いて展開
corr_unstacked = corr.unstack().dropna()

# 絶対値の大きい順に並べ替え
sorted_corr = corr_unstacked.sort_values(ascending=False)

In [7]:
corr_df = sorted_corr.reset_index()
corr_df.columns = ['Feature_1', 'Feature_2', 'Correlation']

In [8]:
corr_df = corr_df[corr_df['Feature_1'] != corr_df['Feature_2']].reset_index(drop=True)

corr_df['pair'] = corr_df.apply(
    lambda x: tuple(sorted([x['Feature_1'], x['Feature_2']])),
    axis=1
)

# 重複を削除
corr_df = corr_df.drop_duplicates(subset='pair').drop(columns='pair').reset_index(drop=True)

In [9]:
corr_df['Correlation'].value_counts(bins=[-1.0, -0.8, -0.6, -0.4, -0.2, 0, 0.2, 0.4, 0.6, 0.8, 1.0])

(0.0, 0.2]        14229
(-0.2, 0.0]        9648
(0.2, 0.4]         7694
(0.4, 0.6]         3455
(-0.4, -0.2]       2879
(0.6, 0.8]         1524
(-0.6, -0.4]       1243
(0.8, 1.0]          697
(-0.8, -0.6]        557
(-1.001, -0.8]      346
Name: count, dtype: int64

In [10]:
# critical_corr_df = corr_df[corr_df['Correlation'].abs() > 0.2].reset_index(drop=True)

## 工事中 下から

In [11]:
remain_corr_df = corr_df[corr_df['Correlation'].abs() <= 0.2].reset_index(drop=True)

In [12]:
pd.concat([remain_corr_df['Feature_1'], remain_corr_df['Feature_2']], axis=0)

0                特許権・実用新案権
1        投資有価証券・関係会社株式・出資金
2                     資産合計
3                     前払費用
4                  有価証券評価益
               ...
23872           償却対象有形固定資産
23873               長期支払手形
23874             負ののれん発生益
23875         棚卸資産の減少額（▲増）
23876               長期支払手形
Length: 47754, dtype: object

In [13]:
low_corr_features =  pd.concat([remain_corr_df['Feature_1'], remain_corr_df['Feature_2']], axis=0).unique().tolist()
# Length = 298 (310 -> 298)

In [14]:
dropped_df = weekly_FR_df.loc[:, ['nikkei'] + low_corr_features]

In [16]:
threshold = 0.8  # 強い相関の基準
corr_matrix = dropped_df.iloc[:, 1:].corr().abs()

# 対角を0にして自分との相関を除外
np.fill_diagonal(corr_matrix.values, 0)

# 各特徴量が他の特徴量とどれくらい強く相関しているかを見る
max_corr = corr_matrix.max()

# どの特徴量も他と0.8以上の相関を持たないものだけ残す
low_corr_features = max_corr[max_corr < threshold].index.tolist()

In [17]:
low_corr_features

['営業費用',
 '法人税等調整額／繰延税金費用',
 'その他営業外費用',
 'その他営業外収益',
 '営業利益',
 'その他流動資産／その他の金融資産',
 'その他流動負債／その他の金融負債',
 '有形固定資産の売却による収入',
 '営業外費用',
 '非支配株主に帰属する当期純利益',
 '固定資産の売却による収入',
 'その他特別利益',
 'その他無形固定資産／その他無形資産',
 '投資有価証券の取得による支出（▲）',
 '投資その他の資産の売却による収入',
 'その他の流動資産の減少額（▲増）',
 'その他の小計欄より上の営業キャッシュフロー',
 '無形固定資産の売却による収入']

## 工事中 上まで

In [ ]:
critical_corr_df = corr_df[corr_df['Correlation'].abs() > 0.2].reset_index(drop=True)

In [ ]:
remain_features = [
    '流動資産',
    '固定資産／非流動資産',
    '有形固定資産',
    '無形固定資産／無形資産',
    '資産合計',
    '流動負債',
    '固定負債／非流動負債',
    '負債合計',
    '株主資本',
    '自己資本／親会社の所有者に帰属する資本',
    '売上高・営業収益',
    '売上総利益',
    '営業利益',
    '経常利益／税金等調整前当期純利益',
    '親会社株主に帰属する当期純利益（連結）／当期利益（単独）',
    '営業活動によるキャッシュフロー',
    '投資活動によるキャッシュフロー',
    '財務活動によるキャッシュフロー',
    '減価償却費',
]

In [ ]:
extract_critical_corr_df = critical_corr_df[(critical_corr_df['Feature_1'].isin(remain_features)) & (~critical_corr_df['Feature_2'].isin(remain_features))]

In [ ]:
delete_features = extract_critical_corr_df['Feature_2'].unique().tolist()

In [ ]:
print(f'{len(delete_features)} features dropped from weekly_FR_df({weekly_FR_df.shape[1]} - {len(delete_features)} = {weekly_FR_df.shape[1] - len(delete_features)} [columns])')

In [ ]:
dropped_weekly_FR_df = weekly_FR_df.drop(columns=delete_features)

In [ ]:
# 相関行列 corr から三角行列を除いて展開
dropped_weekly_FR_df_corr_unstacked = dropped_weekly_FR_df.iloc[:, 2:].corr().unstack().dropna()

# 絶対値の大きい順に並べ替え
sorted_dropped_weekly_FR_df_corr_unstacked = dropped_weekly_FR_df_corr_unstacked.sort_values(ascending=False)

In [ ]:
sorted_dropped_weekly_FR_df_corr_unstacked = sorted_dropped_weekly_FR_df_corr_unstacked.reset_index()
sorted_dropped_weekly_FR_df_corr_unstacked.columns = ['Feature_1', 'Feature_2', 'Correlation']
sorted_dropped_weekly_FR_df_corr_unstacked = sorted_dropped_weekly_FR_df_corr_unstacked[sorted_dropped_weekly_FR_df_corr_unstacked['Feature_1'] != sorted_dropped_weekly_FR_df_corr_unstacked['Feature_2']].reset_index(drop=True)

In [ ]:
print(sorted_dropped_weekly_FR_df_corr_unstacked['Feature_1'].nunique())
sorted_dropped_weekly_FR_df_corr_unstacked['Feature_1'].unique()

In [ ]:
print(corr_df[(corr_df['Correlation'].abs() <= 0.2) & (~corr_df['Feature_1'].isin(delete_features))]['Feature_1'].nunique())
print(corr_df[(corr_df['Correlation'].abs() <= 0.2) & (~corr_df['Feature_1'].isin(delete_features))]['Feature_1'].unique())

In [ ]:
feature_1_low_corr = pd.concat([corr_df[(corr_df['Correlation'].abs() <= 0.2) & (~corr_df['Feature_1'].isin(delete_features))]['Feature_1'], sorted_dropped_weekly_FR_df_corr_unstacked['Feature_1']]).unique()

In [ ]:
print(len(feature_1_low_corr))
feature_1_low_corr

## 特徴選択してDFを再構成

In [18]:
# selected_features = feature_1_low_corr.tolist()

In [19]:
selected_features = low_corr_features

In [20]:
weekly_FR_df_col42 = weekly_FR_df[weekly_FR_df.columns.intersection(selected_features)]

In [21]:
weekly_FR_df_col42 = pd.concat([weekly_FR_df[['nikkei']], weekly_FR_df_col42], axis=1)

In [22]:
tmp = len(weekly_FR_df_col42[weekly_FR_df_col42.iloc[:, 1:].notnull().any(axis=1)])
print(f'valid : {tmp}')
for feature in weekly_FR_df_col42.columns.to_list()[1:]:
    print(f'{feature}: {weekly_FR_df_col42[feature].notnull().sum() / tmp}')

valid : 3084965
その他流動資産／その他の金融資産: 0.9961798594149366
その他無形固定資産／その他無形資産: 0.8868113576653219
その他流動負債／その他の金融負債: 0.9873356747969588
営業費用: 0.9450463781598819
営業利益: 0.9999452181791365
その他営業外収益: 0.9866118416254317
営業外費用: 0.9899373250587932
その他営業外費用: 0.9609891846422893
その他特別利益: 0.5792782089910258
法人税等調整額／繰延税金費用: 0.9743501141828189
非支配株主に帰属する当期純利益: 0.5571019444304879
その他の流動資産の減少額（▲増）: 0.4878946762767163
その他の小計欄より上の営業キャッシュフロー: 0.9379305761977851
固定資産の売却による収入: 1.0
有形固定資産の売却による収入: 1.0
無形固定資産の売却による収入: 1.0
投資その他の資産の売却による収入: 1.0
投資有価証券の取得による支出（▲）: 0.671302915916388

In [23]:
weekly_FR_df_col42

,nikkei,その他流動資産／その他の金融資産,その他無形固定資産／その他無形資産,その他流動負債／その他の金融負債,営業費用,営業利益,その他営業外収益,営業外費用,その他営業外費用,その他特別利益,法人税等調整額／繰延税金費用,非支配株主に帰属する当期純利益,その他の流動資産の減少額（▲増）,その他の小計欄より上の営業キャッシュフロー,固定資産の売却による収入,有形固定資産の売却による収入,無形固定資産の売却による収入,投資その他の資産の売却による収入,投資有価証券の取得による支出（▲）
0,N0000001,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,N0000002,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,N0000003,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,N0000004,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,N0000005,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5524987,N0091164,189.0,2.0,136.0,2312.0,-121.0,3.0,23.0,4.0,NaN,25.0,NaN,-1.0,-147.0,463.0,0.0,0.0,0.0,-281.0
5524988,N0091165,50.0,6.0,424.0,1823.0,958.0,3.0,1.0,0.0,NaN,-30.0,NaN,NaN,-175.0,0.0,0.0,0.0,0.0,-59.0
5524989,N0091290,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5524990,N0091517,1577.0,5433.0,1518.0,50493.0,4806.0,118.0,-21.0,27.0,NaN,-444.0,0.0,NaN,589.5,658.0,0.0,0.0,658.0,-57.0
5524991,N0091607,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [24]:
weekly_FR_df_col42['week_id'] = (weekly_FR_df_col42.index / 4608).astype(int)

In [25]:
new_order = ['nikkei', 'week_id'] + selected_features[1:-1]
weekly_FR_df_col42 = weekly_FR_df_col42.reindex(columns=new_order)

In [26]:

weekly_FR_df_col42

,nikkei,week_id,法人税等調整額／繰延税金費用,その他営業外費用,その他営業外収益,営業利益,その他流動資産／その他の金融資産,その他流動負債／その他の金融負債,有形固定資産の売却による収入,営業外費用,非支配株主に帰属する当期純利益,固定資産の売却による収入,その他特別利益,その他無形固定資産／その他無形資産,投資有価証券の取得による支出（▲）,投資その他の資産の売却による収入,その他の流動資産の減少額（▲増）,その他の小計欄より上の営業キャッシュフロー
0,N0000001,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,N0000002,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,N0000003,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,N0000004,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,N0000005,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5524987,N0091164,1198,25.0,4.0,3.0,-121.0,189.0,136.0,0.0,23.0,NaN,463.0,NaN,2.0,-281.0,0.0,-1.0,-147.0
5524988,N0091165,1198,-30.0,0.0,3.0,958.0,50.0,424.0,0.0,1.0,NaN,0.0,NaN,6.0,-59.0,0.0,NaN,-175.0
5524989,N0091290,1198,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5524990,N0091517,1198,-444.0,27.0,118.0,4806.0,1577.0,1518.0,0.0,-21.0,0.0,658.0,NaN,5433.0,-57.0,658.0,NaN,589.5
5524991,N0091607,1198,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [27]:
weekly_FR_df_col42.to_csv('../../data/main/master/product/weekly_FR_df_col42.csv', index=False)

## 異常値検知

    - PERまで計算してから実施.

In [43]:
# IOne-Class SVM
import pandas as pd
from sklearn.svm import OneClassSVM
import numpy as np

In [44]:
weekly_FR_df_col42 = pd.read_csv('../../data/main/master/product/weekly_FR_df_col42.csv').sort_values(by=['nikkei', 'week_id']).reset_index(drop=True)
TR_df = pd.read_csv('../../data/main/master/product/weekly_TR(wed)_Tech.csv').sort_values(by=['nikkei', 'week_id']).reset_index(drop=True)
FA_df = pd.read_csv('../../data/main/master/product/weekly_FA_v2.csv').sort_values(by=['nikkei', 'week_id']).reset_index(drop=True)

In [46]:
weekly_FR_df_col42

,nikkei,week_id,法人税等調整額／繰延税金費用,その他営業外費用,その他営業外収益,営業利益,その他流動資産／その他の金融資産,その他流動負債／その他の金融負債,有形固定資産の売却による収入,営業外費用,非支配株主に帰属する当期純利益,固定資産の売却による収入,その他特別利益,その他無形固定資産／その他無形資産,投資有価証券の取得による支出（▲）,投資その他の資産の売却による収入,その他の流動資産の減少額（▲増）,その他の小計欄より上の営業キャッシュフロー
0,N0000001,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,N0000001,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,N0000001,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,N0000001,3,-342.0,110.0,78.0,2358.0,1399.0,3801.0,226.0,359.0,15.0,226.0,0.0,216.0,-354.0,0.0,-111.0,-18.0
4,N0000001,4,150.0,14.0,69.0,1881.0,2788.0,9201.0,0.0,128.0,-26.0,5.0,0.0,524.0,-206.5,0.0,2291.0,-347.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5524987,N0091607,1194,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5524988,N0091607,1195,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5524989,N0091607,1196,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5524990,N0091607,1197,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5524991,N0091607,1198,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [47]:
TR_df.head()

,nikkei,week_id,open,weekly_high,weekly_low,close,SMA_5,SMA_15,SMA_40,RSI_26,...,MACD,MACD_signal,MACD_hist,STC_fk,STC_fd,MOM_10,BB2U,BB1U,BB1L,BB2L
0,N0000001,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,N0000001,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,N0000001,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,N0000001,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,N0000001,4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [48]:
TR_df.columns.to_list()

['nikkei',
 'week_id',
 'open',
 'weekly_high',
 'weekly_low',
 'close',
 'SMA_5',
 'SMA_15',
 'SMA_40',
 'RSI_26',
 'RSI_14',
 'RSI_9',
 'MACD',
 'MACD_signal',
 'MACD_hist',
 'STC_fk',
 'STC_fd',
 'MOM_10',
 'BB2U',
 'BB1U',
 'BB1L',
 'BB2L']

In [49]:
FA_df.head()

,nikkei,week_id,発行済株式数,１株当たり配当金,時価総額,PER,EPS,PBR,BPS,PSR,...,売上総利益の増加額,営業利益の増加額,経常利益／税金等調整前当期純利益の増加額,売上高総利益率,売上高営業利益率,売上高経常利益率,流動資産率,固定資産率,現金及び現金同等物の増加額,純有利子負債
0,N0000001,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,N0000001,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,N0000001,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,N0000001,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,N0000001,4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [76]:
FA_df.count()

nikkei                  5524992
week_id                 5524992
発行済株式数                  1556151
１株当たり配当金                1560470
時価総額                    1298352
PER                     1295925
EPS                     1552444
PBR                     1295925
BPS                     1552467
PSR                     1295923
SPS                     1552428
EV                      1294394
CFPS                    1550878
PCFR                    1294382
EBITDA                  1555829
EV/EBITDA               1293952
内部留保                    1552240
サスティナブル成長率              1494536
配当性向                    1552239
ROE                     1498095
ROA                     1498095
自己資本比率                  1557156
流動比率                    1557166
固定比率                    1557166
総資産回転率                  1557116
株主資本回転率                 1557116
ギアリング比率                 1555948
フリーキャッシュフロー             1554891
売上高・営業収益の増加額             873339
売上総利益の増加額                873047
営業利益の増加額                 873405
経常利益／税金等調整前当期純利益の増加額     873405
売上高総利益率                 1524187
売上高営業利益率                1524187
売上高経常利益率                1524187
流動資産率                   1557166
固定資産率                   1557166
現金及び現金同等物の増加額            871471
純有利子負債                  1555419
dtype: int64

In [50]:
flag_mask = TR_df.iloc[:, 2:].notnull().any(axis=1)
weekly_FR_df_col42['上場フラグ'] = np.nan
weekly_FR_df_col42.loc[flag_mask, '上場フラグ'] = 1
weekly_FR_df_col42.loc[~flag_mask, '上場フラグ'] = 0

In [51]:
weekly_FR_df_col42.replace([0], np.nan, inplace=True)
FA_df.replace([np.inf], 1e10, inplace=True)
FA_df.replace([-np.inf], -1e10, inplace=True)
BIG_df = pd.concat([weekly_FR_df_col42, FA_df.iloc[:, 2:], TR_df.iloc[:, 2:]], axis=1)
print(len(BIG_df))

5524992

In [53]:
def detect_anomalies(group: pd.DataFrame):
    print('\r', f'Detecting anomalies for group: {group.name}', end=' ') 
    data = group[group['上場フラグ'] == 1].iloc[:, 2:]
    if len(data.values) == 0: 
        pred = np.nan
        score = np.nan
        print('\n', group.name, 'has no listed weeks.')
    else:
        data = data.fillna(0)
        clf = OneClassSVM(nu=0.05, kernel="rbf")
        clf.fit(data)
        pred = clf.predict(data)
        score = clf.decision_function(data)
    group.loc[data.index, 'anomaly'] = pred
    group.loc[data.index, 'anomaly_score'] = score
    return group

In [54]:
BIG_df = pd.concat([weekly_FR_df_col42, FA_df.iloc[:, 2:], TR_df.iloc[:, 2:]], axis=1)
print(len(BIG_df))

5524992

In [55]:
group_df = (
    BIG_df
    .groupby('nikkei')
    .apply(detect_anomalies)
).reset_index(drop=True)

 Detecting anomalies for group: N0000088
 N0000088 has no listed weeks.
 Detecting anomalies for group: N0000176
 N0000176 has no listed weeks.
 Detecting anomalies for group: N0000197
 N0000197 has no listed weeks.
 Detecting anomalies for group: N0000214
 N0000214 has no listed weeks.
 Detecting anomalies for group: N0000242
 N0000242 has no listed weeks.
 Detecting anomalies for group: N0000277
 N0000277 has no listed weeks.
 Detecting anomalies for group: N0000280
 N0000280 has no listed weeks.
 Detecting anomalies for group: N0000427
 N0000427 has no listed weeks.
 Detecting anomalies for group: N0000440
 N0000440 has no listed weeks.
 Detecting anomalies for group: N0000511
 N0000511 has no listed weeks.
 Detecting anomalies for group: N0000534
 N0000534 has no listed weeks.
 Detecting anomalies for group: N0000633
 N0000633 has no listed weeks.
 Detecting anomalies for group: N0000666
 N0000666 has no listed weeks.
 Detecting anomalies for group: N0000724
 N0000724 has no listed weeks.
 Detecting anomalies for group: N0000825
 N0000825 has no listed weeks.
 Detecting anomalies for group: N0000916
 N0000916 has no listed weeks.
 Detecting anomalies for group: N0000957
 N0000957 has no listed weeks.
 Detecting anomalies for group: N0000992
 N0000992 has no listed weeks.
 Detecting anomalies for group: N0001021
 N0001021 has no listed weeks.
 Detecting anomalies for group: N0001043
 N0001043 has no listed weeks.
 Detecting anomalies for group: N0001085
 N0001085 has no listed weeks.
 Detecting anomalies for group: N0001128
 N0001128 has no listed weeks.
 Detecting anomalies for group: N0001155
 N0001155 has no listed weeks.
 Detecting anomalies for group: N0001200
 N0001200 has no listed weeks.
 Detecting anomalies for group: N0001245
 N0001245 has no listed weeks.
 Detecting anomalies for group: N0001413
 N0001413 has no listed weeks.
 Detecting anomalies for group: N0001557
 N0001557 has no listed weeks.
 Detecting anomalies for group: N0001606
 N0001606 has no listed weeks.
 Detecting anomalies for group: N0001788
 N0001788 has no listed weeks.
 Detecting anomalies for group: N0001814
 N0001814 has no listed weeks.
 Detecting anomalies for group: N0001842
 N0001842 has no listed weeks.
 Detecting anomalies for group: N0001854
 N0001854 has no listed weeks.
 Detecting anomalies for group: N0001921
 N0001921 has no listed weeks.
 Detecting anomalies for group: N0001971
 N0001971 has no listed weeks.
 Detecting anomalies for group: N0001975
 N0001975 has no listed weeks.
 Detecting anomalies for group: N0001985
 N0001985 has no listed weeks.
 Detecting anomalies for group: N0001991
 N0001991 has no listed weeks.
 Detecting anomalies for group: N0002448
 N0002448 has no listed weeks.
 Detecting anomalies for group: N0002528
 N0002528 has no listed weeks.
 Detecting anomalies for group: N0002677
 N0002677 has no listed weeks.
 Detecting anomalies for group: N0002978
 N0002978 has no listed weeks.
 Detecting anomalies for group: N0003454
 N0003454 has no listed weeks.
 Detecting anomalies for group: N0003651
 N0003651 has no listed weeks.
 Detecting anomalies for group: N0004155
 N0004155 has no listed weeks.
 Detecting anomalies for group: N0006248
 N0006248 has no listed weeks.
 Detecting anomalies for group: N0006762
 N0006762 has no listed weeks.
 Detecting anomalies for group: N0007095
 N0007095 has no listed weeks.
 Detecting anomalies for group: N0007107
 N0007107 has no listed weeks.
 Detecting anomalies for group: N0007329
 N0007329 has no listed weeks.
 Detecting anomalies for group: N0007657
 N0007657 has no listed weeks.
 Detecting anomalies for group: N0008577
 N0008577 has no listed weeks.
 Detecting anomalies for group: N0009126
 N0009126 has no listed weeks.
 Detecting anomalies for group: N0009436
 N0009436 has no listed weeks.
 Detecting anomalies for group: N0009613
 N0009613 has no listed weeks.
 Detecting anomalies for group: N0010198
 N0010198 has no listed weeks.
 Detecting anomalies for group: N0010503
 N0010503 has no listed weeks.
 Detecting anomalies for group: N0010546
 N0010546 has no listed weeks.
 Detecting anomalies for group: N0010760
 N0010760 has no listed weeks.
 Detecting anomalies for group: N0010770
 N0010770 has no listed weeks.
 Detecting anomalies for group: N0011066
 N0011066 has no listed weeks.
 Detecting anomalies for group: N0011337
 N0011337 has no listed weeks.
 Detecting anomalies for group: N0011407
 N0011407 has no listed weeks.
 Detecting anomalies for group: N0011450
 N0011450 has no listed weeks.
 Detecting anomalies for group: N0011978
 N0011978 has no listed weeks.
 Detecting anomalies for group: N0011987
 N0011987 has no listed weeks.
 Detecting anomalies for group: N0012040
 N0012040 has no listed weeks.
 Detecting anomalies for group: N0012105
 N0012105 has no listed weeks.
 Detecting anomalies for group: N0012211
 N0012211 has no listed weeks.
 Detecting anomalies for group: N0012225
 N0012225 has no listed weeks.
 Detecting anomalies for group: N0012240
 N0012240 has no listed weeks.
 Detecting anomalies for group: N0012607
 N0012607 has no listed weeks.
 Detecting anomalies for group: N0013401
 N0013401 has no listed weeks.
 Detecting anomalies for group: N0013565
 N0013565 has no listed weeks.
 Detecting anomalies for group: N0013936
 N0013936 has no listed weeks.
 Detecting anomalies for group: N0014271
 N0014271 has no listed weeks.
 Detecting anomalies for group: N0014333
 N0014333 has no listed weeks.
 Detecting anomalies for group: N0014983
 N0014983 has no listed weeks.
 Detecting anomalies for group: N0015005
 N0015005 has no listed weeks.
 Detecting anomalies for group: N0015174
 N0015174 has no listed weeks.
 Detecting anomalies for group: N0015222
 N0015222 has no listed weeks.
 Detecting anomalies for group: N0015424
 N0015424 has no listed weeks.
 Detecting anomalies for group: N0015813
 N0015813 has no listed weeks.
 Detecting anomalies for group: N0016013
 N0016013 has no listed weeks.
 Detecting anomalies for group: N0016022
 N0016022 has no listed weeks.
 Detecting anomalies for group: N0016094
 N0016094 has no listed weeks.
 Detecting anomalies for group: N0016121
 N0016121 has no listed weeks.
 Detecting anomalies for group: N0016181
 N0016181 has no listed weeks.
 Detecting anomalies for group: N0016193
 N0016193 has no listed weeks.
 Detecting anomalies for group: N0016213
 N0016213 has no listed weeks.
 Detecting anomalies for group: N0016301
 N0016301 has no listed weeks.
 Detecting anomalies for group: N0016332
 N0016332 has no listed weeks.
 Detecting anomalies for group: N0016388
 N0016388 has no listed weeks.
 Detecting anomalies for group: N0016534
 N0016534 has no listed weeks.
 Detecting anomalies for group: N0016604
 N0016604 has no listed weeks.
 Detecting anomalies for group: N0016902
 N0016902 has no listed weeks.
 Detecting anomalies for group: N0018453
 N0018453 has no listed weeks.
 Detecting anomalies for group: N0018498
 N0018498 has no listed weeks.
 Detecting anomalies for group: N0018836
 N0018836 has no listed weeks.
 Detecting anomalies for group: N0019050
 N0019050 has no listed weeks.
 Detecting anomalies for group: N0019904
 N0019904 has no listed weeks.
 Detecting anomalies for group: N0020222
 N0020222 has no listed weeks.
 Detecting anomalies for group: N0021062
 N0021062 has no listed weeks.
 Detecting anomalies for group: N0021160
 N0021160 has no listed weeks.
 Detecting anomalies for group: N0022184
 N0022184 has no listed weeks.
 Detecting anomalies for group: N0022264
 N0022264 has no listed weeks.
 Detecting anomalies for group: N0022903
 N0022903 has no listed weeks.
 Detecting anomalies for group: N0023185
 N0023185 has no listed weeks.
 Detecting anomalies for group: N0023942
 N0023942 has no listed weeks.
 Detecting anomalies for group: N0023982
 N0023982 has no listed weeks.
 Detecting anomalies for group: N0024143
 N0024143 has no listed weeks.
 Detecting anomalies for group: N0029452
 N0029452 has no listed weeks.
 Detecting anomalies for group: N0029789
 N0029789 has no listed weeks.
 Detecting anomalies for group: N0030003
 N0030003 has no listed weeks.
 Detecting anomalies for group: N0030007
 N0030007 has no listed weeks.
 Detecting anomalies for group: N0030081
 N0030081 has no listed weeks.
 Detecting anomalies for group: N0030100
 N0030100 has no listed weeks.
 Detecting anomalies for group: N0030177
 N0030177 has no listed weeks.
 Detecting anomalies for group: N0030217
 N0030217 has no listed weeks.
 Detecting anomalies for group: N0030344
 N0030344 has no listed weeks.
 Detecting anomalies for group: N0030359
 N0030359 has no listed weeks.
 Detecting anomalies for group: N0030396
 N0030396 has no listed weeks.
 Detecting anomalies for group: N0030473
 N0030473 has no listed weeks.
 Detecting anomalies for group: N0030587
 N0030587 has no listed weeks.
 Detecting anomalies for group: N0030687
 N0030687 has no listed weeks.
 Detecting anomalies for group: N0030807
 N0030807 has no listed weeks.
 Detecting anomalies for group: N0030845
 N0030845 has no listed weeks.
 Detecting anomalies for group: N0030865
 N0030865 has no listed weeks.
 Detecting anomalies for group: N0030969
 N0030969 has no listed weeks.
 Detecting anomalies for group: N0030983
 N0030983 has no listed weeks.
 Detecting anomalies for group: N0031086
 N0031086 has no listed weeks.
 Detecting anomalies for group: N0031235
 N0031235 has no listed weeks.
 Detecting anomalies for group: N0031573
 N0031573 has no listed weeks.
 Detecting anomalies for group: N0031621
 N0031621 has no listed weeks.
 Detecting anomalies for group: N0031661
 N0031661 has no listed weeks.
 Detecting anomalies for group: N0031687
 N0031687 has no listed weeks.
 Detecting anomalies for group: N0031728
 N0031728 has no listed weeks.
 Detecting anomalies for group: N0031761
 N0031761 has no listed weeks.
 Detecting anomalies for group: N0031826
 N0031826 has no listed weeks.
 Detecting anomalies for group: N0031841
 N0031841 has no listed weeks.
 Detecting anomalies for group: N0031909
 N0031909 has no listed weeks.
 Detecting anomalies for group: N0031910
 N0031910 has no listed weeks.
 Detecting anomalies for group: N0031933
 N0031933 has no listed weeks.
 Detecting anomalies for group: N0031977
 N0031977 has no listed weeks.
 Detecting anomalies for group: N0032005
 N0032005 has no listed weeks.
 Detecting anomalies for group: N0032055
 N0032055 has no listed weeks.
 Detecting anomalies for group: N0032063
 N0032063 has no listed weeks.
 Detecting anomalies for group: N0032149
 N0032149 has no listed weeks.
 Detecting anomalies for group: N0032223
 N0032223 has no listed weeks.
 Detecting anomalies for group: N0032254
 N0032254 has no listed weeks.
 Detecting anomalies for group: N0032283
 N0032283 has no listed weeks.
 Detecting anomalies for group: N0032292
 N0032292 has no listed weeks.
 Detecting anomalies for group: N0032293
 N0032293 has no listed weeks.
 Detecting anomalies for group: N0032345
 N0032345 has no listed weeks.
 Detecting anomalies for group: N0032346
 N0032346 has no listed weeks.
 Detecting anomalies for group: N0032347
 N0032347 has no listed weeks.
 Detecting anomalies for group: N0032382
 N0032382 has no listed weeks.
 Detecting anomalies for group: N0032388
 N0032388 has no listed weeks.
 Detecting anomalies for group: N0032397
 N0032397 has no listed weeks.
 Detecting anomalies for group: N0032428
 N0032428 has no listed weeks.
 Detecting anomalies for group: N0032452
 N0032452 has no listed weeks.
 Detecting anomalies for group: N0032465
 N0032465 has no listed weeks.
 Detecting anomalies for group: N0032471
 N0032471 has no listed weeks.
 Detecting anomalies for group: N0032491
 N0032491 has no listed weeks.
 Detecting anomalies for group: N0032497
 N0032497 has no listed weeks.
 Detecting anomalies for group: N0032505
 N0032505 has no listed weeks.
 Detecting anomalies for group: N0032510
 N0032510 has no listed weeks.
 Detecting anomalies for group: N0032518
 N0032518 has no listed weeks.
 Detecting anomalies for group: N0032524
 N0032524 has no listed weeks.
 Detecting anomalies for group: N0032535
 N0032535 has no listed weeks.
 Detecting anomalies for group: N0032551
 N0032551 has no listed weeks.
 Detecting anomalies for group: N0032578
 N0032578 has no listed weeks.
 Detecting anomalies for group: N0032581
 N0032581 has no listed weeks.
 Detecting anomalies for group: N0032582
 N0032582 has no listed weeks.
 Detecting anomalies for group: N0032584
 N0032584 has no listed weeks.
 Detecting anomalies for group: N0032616
 N0032616 has no listed weeks.
 Detecting anomalies for group: N0032617
 N0032617 has no listed weeks.
 Detecting anomalies for group: N0032622
 N0032622 has no listed weeks.
 Detecting anomalies for group: N0032639
 N0032639 has no listed weeks.
 Detecting anomalies for group: N0032674
 N0032674 has no listed weeks.
 Detecting anomalies for group: N0032676
 N0032676 has no listed weeks.
 Detecting anomalies for group: N0032705
 N0032705 has no listed weeks.
 Detecting anomalies for group: N0032714
 N0032714 has no listed weeks.
 Detecting anomalies for group: N0032715
 N0032715 has no listed weeks.
 Detecting anomalies for group: N0032730
 N0032730 has no listed weeks.
 Detecting anomalies for group: N0032744
 N0032744 has no listed weeks.
 Detecting anomalies for group: N0032746
 N0032746 has no listed weeks.
 Detecting anomalies for group: N0032779
 N0032779 has no listed weeks.
 Detecting anomalies for group: N0032783
 N0032783 has no listed weeks.
 Detecting anomalies for group: N0032784
 N0032784 has no listed weeks.
 Detecting anomalies for group: N0032791
 N0032791 has no listed weeks.
 Detecting anomalies for group: N0032800
 N0032800 has no listed weeks.
 Detecting anomalies for group: N0032801
 N0032801 has no listed weeks.
 Detecting anomalies for group: N0032803
 N0032803 has no listed weeks.
 Detecting anomalies for group: N0032808
 N0032808 has no listed weeks.
 Detecting anomalies for group: N0032813
 N0032813 has no listed weeks.
 Detecting anomalies for group: N0032818
 N0032818 has no listed weeks.
 Detecting anomalies for group: N0032821
 N0032821 has no listed weeks.
 Detecting anomalies for group: N0032822
 N0032822 has no listed weeks.
 Detecting anomalies for group: N0032835
 N0032835 has no listed weeks.
 Detecting anomalies for group: N0032845
 N0032845 has no listed weeks.
 Detecting anomalies for group: N0032854
 N0032854 has no listed weeks.
 Detecting anomalies for group: N0032859
 N0032859 has no listed weeks.
 Detecting anomalies for group: N0032861
 N0032861 has no listed weeks.
 Detecting anomalies for group: N0032863
 N0032863 has no listed weeks.
 Detecting anomalies for group: N0032877
 N0032877 has no listed weeks.
 Detecting anomalies for group: N0032882
 N0032882 has no listed weeks.
 Detecting anomalies for group: N0032904
 N0032904 has no listed weeks.
 Detecting anomalies for group: N0032905
 N0032905 has no listed weeks.
 Detecting anomalies for group: N0032907
 N0032907 has no listed weeks.
 Detecting anomalies for group: N0032908
 N0032908 has no listed weeks.
 Detecting anomalies for group: N0032909
 N0032909 has no listed weeks.
 Detecting anomalies for group: N0032911
 N0032911 has no listed weeks.
 Detecting anomalies for group: N0032912
 N0032912 has no listed weeks.
 Detecting anomalies for group: N0032913
 N0032913 has no listed weeks.
 Detecting anomalies for group: N0032915
 N0032915 has no listed weeks.
 Detecting anomalies for group: N0032917
 N0032917 has no listed weeks.
 Detecting anomalies for group: N0032918
 N0032918 has no listed weeks.
 Detecting anomalies for group: N0032919
 N0032919 has no listed weeks.
 Detecting anomalies for group: N0032920
 N0032920 has no listed weeks.
 Detecting anomalies for group: N0032921
 N0032921 has no listed weeks.
 Detecting anomalies for group: N0032922
 N0032922 has no listed weeks.
 Detecting anomalies for group: N0032923
 N0032923 has no listed weeks.
 Detecting anomalies for group: N0032924
 N0032924 has no listed weeks.
 Detecting anomalies for group: N0032925
 N0032925 has no listed weeks.
 Detecting anomalies for group: N0032927
 N0032927 has no listed weeks.
 Detecting anomalies for group: N0032929
 N0032929 has no listed weeks.
 Detecting anomalies for group: N0032930
 N0032930 has no listed weeks.
 Detecting anomalies for group: N0032932
 N0032932 has no listed weeks.
 Detecting anomalies for group: N0032934
 N0032934 has no listed weeks.
 Detecting anomalies for group: N0032935
 N0032935 has no listed weeks.
 Detecting anomalies for group: N0032936
 N0032936 has no listed weeks.
 Detecting anomalies for group: N0032937
 N0032937 has no listed weeks.
 Detecting anomalies for group: N0032940
 N0032940 has no listed weeks.
 Detecting anomalies for group: N0032941
 N0032941 has no listed weeks.
 Detecting anomalies for group: N0032942
 N0032942 has no listed weeks.
 Detecting anomalies for group: N0032943
 N0032943 has no listed weeks.
 Detecting anomalies for group: N0032946
 N0032946 has no listed weeks.
 Detecting anomalies for group: N0032947
 N0032947 has no listed weeks.
 Detecting anomalies for group: N0032948
 N0032948 has no listed weeks.
 Detecting anomalies for group: N0032951
 N0032951 has no listed weeks.
 Detecting anomalies for group: N0032952
 N0032952 has no listed weeks.
 Detecting anomalies for group: N0032953
 N0032953 has no listed weeks.
 Detecting anomalies for group: N0032954
 N0032954 has no listed weeks.
 Detecting anomalies for group: N0032955
 N0032955 has no listed weeks.
 Detecting anomalies for group: N0032958
 N0032958 has no listed weeks.
 Detecting anomalies for group: N0032959
 N0032959 has no listed weeks.
 Detecting anomalies for group: N0032960
 N0032960 has no listed weeks.
 Detecting anomalies for group: N0032961
 N0032961 has no listed weeks.
 Detecting anomalies for group: N0032963
 N0032963 has no listed weeks.
 Detecting anomalies for group: N0032965
 N0032965 has no listed weeks.
 Detecting anomalies for group: N0032966
 N0032966 has no listed weeks.
 Detecting anomalies for group: N0032967
 N0032967 has no listed weeks.
 Detecting anomalies for group: N0032968
 N0032968 has no listed weeks.
 Detecting anomalies for group: N0032969
 N0032969 has no listed weeks.
 Detecting anomalies for group: N0032972
 N0032972 has no listed weeks.
 Detecting anomalies for group: N0032974
 N0032974 has no listed weeks.
 Detecting anomalies for group: N0032975
 N0032975 has no listed weeks.
 Detecting anomalies for group: N0032976
 N0032976 has no listed weeks.
 Detecting anomalies for group: N0032977
 N0032977 has no listed weeks.
 Detecting anomalies for group: N0032978
 N0032978 has no listed weeks.
 Detecting anomalies for group: N0032979
 N0032979 has no listed weeks.
 Detecting anomalies for group: N0032980
 N0032980 has no listed weeks.
 Detecting anomalies for group: N0032981
 N0032981 has no listed weeks.
 Detecting anomalies for group: N0032982
 N0032982 has no listed weeks.
 Detecting anomalies for group: N0032984
 N0032984 has no listed weeks.
 Detecting anomalies for group: N0032985
 N0032985 has no listed weeks.
 Detecting anomalies for group: N0032986
 N0032986 has no listed weeks.
 Detecting anomalies for group: N0032988
 N0032988 has no listed weeks.
 Detecting anomalies for group: N0032989
 N0032989 has no listed weeks.
 Detecting anomalies for group: N0032990
 N0032990 has no listed weeks.
 Detecting anomalies for group: N0032991
 N0032991 has no listed weeks.
 Detecting anomalies for group: N0032992
 N0032992 has no listed weeks.
 Detecting anomalies for group: N0032993
 N0032993 has no listed weeks.
 Detecting anomalies for group: N0032995
 N0032995 has no listed weeks.
 Detecting anomalies for group: N0032996
 N0032996 has no listed weeks.
 Detecting anomalies for group: N0032997
 N0032997 has no listed weeks.
 Detecting anomalies for group: N0032998
 N0032998 has no listed weeks.
 Detecting anomalies for group: N0032999

C:\Users\Ito Yuki\AppData\Local\Temp\ipykernel_6764\1409675680.py:4: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  .apply(detect_anomalies)

In [56]:
print(f'\nAnomaly detection completed ({len(group_df[(group_df['nikkei'] == 'N0000001') & (group_df['anomaly'] == -1)])} / {len(group_df[(group_df['nikkei'] == 'N0000001')])}).')
group_df[(group_df['nikkei'] == 'N0000001') & (group_df['anomaly'] == -1)].to_csv('tmp.csv')

Anomaly detection completed (59 / 1199).

In [57]:
TR_df[TR_df['nikkei'] == 'N0000088'].count()

nikkei         1199
week_id        1199
open              0
weekly_high       0
weekly_low        0
close             0
SMA_5             0
SMA_15            0
SMA_40            0
RSI_26            0
RSI_14            0
RSI_9             0
MACD              0
MACD_signal       0
MACD_hist         0
STC_fk            0
STC_fd            0
MOM_10            0
BB2U              0
BB1U              0
BB1L              0
BB2L              0
dtype: int64

In [41]:
delete_nikkei = [
	'N0000088', 
	'N0000176', 
	'N0000197', 
	'N0000214', 
	'N0000242', 
	'N0000277', 
	'N0000280', 
	'N0000427', 
	'N0000440', 
	'N0000511', 
	'N0000534', 
	'N0000633', 
	'N0000666', 
	'N0000724', 
	'N0000825', 
	'N0000916', 
	'N0000957', 
	'N0000992', 
	'N0001021', 
	'N0001043', 
	'N0001085', 
	'N0001128', 
	'N0001155', 
	'N0001200', 
	'N0001245', 
	'N0001413', 
	'N0001557', 
	'N0001606', 
	'N0001788', 
	'N0001814', 
	'N0001842', 
	'N0001854', 
	'N0001921', 
	'N0001971', 
	'N0001975', 
	'N0001985', 
	'N0001991', 
	'N0002448', 
	'N0002528', 
	'N0002677', 
	'N0002978', 
	'N0003454', 
	'N0003651', 
	'N0004155', 
	'N0006248', 
	'N0006762', 
	'N0007095', 
	'N0007107', 
	'N0007329', 
	'N0007657', 
	'N0008577', 
	'N0009126', 
	'N0009436', 
	'N0009613', 
	'N0010198', 
	'N0010503', 
	'N0010546', 
	'N0010760', 
	'N0010770', 
	'N0011066', 
	'N0011337', 
	'N0011407', 
	'N0011450', 
	'N0011978', 
	'N0011987', 
	'N0012040', 
	'N0012105', 
	'N0012211', 
	'N0012225', 
	'N0012240', 
	'N0012607', 
	'N0013401', 
	'N0013565', 
	'N0013936', 
	'N0014271', 
	'N0014333', 
	'N0014983', 
	'N0015005', 
	'N0015174', 
	'N0015222', 
	'N0015424', 
	'N0015813', 
	'N0016013', 
	'N0016022', 
	'N0016094', 
	'N0016121', 
	'N0016181', 
	'N0016193', 
	'N0016213', 
	'N0016301', 
	'N0016332', 
	'N0016388', 
	'N0016534', 
	'N0016604', 
	'N0016902', 
	'N0018453', 
	'N0018498', 
	'N0018836', 
	'N0019050', 
	'N0019904', 
	'N0020222', 
	'N0021062', 
	'N0021160', 
	'N0022184', 
	'N0022264', 
	'N0022903', 
	'N0023185', 
	'N0023942', 
	'N0023982', 
	'N0024143', 
	'N0029452', 
	'N0029789', 
	'N0030003', 
	'N0030007', 
	'N0030081', 
	'N0030100', 
	'N0030177', 
	'N0030217', 
	'N0030344', 
	'N0030359', 
	'N0030396', 
	'N0030473', 
	'N0030587', 
	'N0030687', 
	'N0030807', 
	'N0030845', 
	'N0030865', 
	'N0030969', 
	'N0030983', 
	'N0031086', 
	'N0031235', 
	'N0031573', 
	'N0031621', 
	'N0031661', 
	'N0031687', 
	'N0031728', 
	'N0031761', 
	'N0031826', 
	'N0031841', 
	'N0031909', 
	'N0031910', 
	'N0031933', 
	'N0031977', 
	'N0032005', 
	'N0032055', 
	'N0032063', 
	'N0032149', 
	'N0032223', 
	'N0032254', 
	'N0032283', 
	'N0032292', 
	'N0032293', 
	'N0032345', 
	'N0032346', 
	'N0032347', 
	'N0032382', 
	'N0032388', 
	'N0032397', 
	'N0032428', 
	'N0032452', 
	'N0032465', 
	'N0032471', 
	'N0032491', 
	'N0032497', 
	'N0032505', 
	'N0032510', 
	'N0032518', 
	'N0032524', 
	'N0032535', 
	'N0032551', 
	'N0032578', 
	'N0032581', 
	'N0032582', 
	'N0032584', 
	'N0032616', 
	'N0032617', 
	'N0032622', 
	'N0032639', 
	'N0032674', 
	'N0032676', 
	'N0032705', 
	'N0032714', 
	'N0032715', 
	'N0032730', 
	'N0032744', 
	'N0032746', 
	'N0032779', 
	'N0032783', 
	'N0032784', 
	'N0032791', 
	'N0032800', 
	'N0032801', 
	'N0032803', 
	'N0032808', 
	'N0032813', 
	'N0032818', 
	'N0032821', 
	'N0032822', 
	'N0032835', 
	'N0032845', 
	'N0032854', 
	'N0032859', 
	'N0032861', 
	'N0032863', 
	'N0032877', 
	'N0032882', 
	'N0032904', 
	'N0032905', 
	'N0032907', 
	'N0032908', 
	'N0032909', 
	'N0032911', 
	'N0032912', 
	'N0032913', 
	'N0032915', 
	'N0032917', 
	'N0032918', 
	'N0032919', 
	'N0032920', 
	'N0032921', 
	'N0032922', 
	'N0032923', 
	'N0032924', 
	'N0032925', 
	'N0032927', 
	'N0032929', 
	'N0032930', 
	'N0032932', 
	'N0032934', 
	'N0032935', 
	'N0032936', 
	'N0032937', 
	'N0032940', 
	'N0032941', 
	'N0032942', 
	'N0032943', 
	'N0032946', 
	'N0032947', 
	'N0032948', 
	'N0032951', 
	'N0032952', 
	'N0032953', 
	'N0032954', 
	'N0032955', 
	'N0032958', 
	'N0032959', 
	'N0032960', 
	'N0032961', 
	'N0032963', 
	'N0032965', 
	'N0032966', 
	'N0032967', 
	'N0032968', 
	'N0032969', 
	'N0032972', 
	'N0032974', 
	'N0032975', 
	'N0032976', 
	'N0032977', 
	'N0032978', 
	'N0032979', 
	'N0032980', 
	'N0032981', 
	'N0032982', 
	'N0032984', 
	'N0032985', 
	'N0032986', 
	'N0032988', 
	'N0032989', 
	'N0032990', 
	'N0032991', 
	'N0032992', 
	'N0032993', 
	'N0032995', 
	'N0032996', 
	'N0032997', 
	'N0032998', 
	'N0032999', 
	'N0033001', 
	'N0033002', 
	'N0033003', 
	'N0033005', 
	'N0033006', 
	'N0033007', 
	'N0033008', 
	'N0033009', 
	'N0033010', 
	'N0033011', 
	'N0033012', 
	'N0033013', 
	'N0033014', 
	'N0033015', 
	'N0033017', 
	'N0033018', 
	'N0033019', 
	'N0033020', 
	'N0033021', 
	'N0033022', 
	'N0033023', 
	'N0033024', 
	'N0033025', 
	'N0033026', 
	'N0033027', 
	'N0033028', 
	'N0033030', 
	'N0035150', 
	'N0038827', 
	'N0038831', 
	'N0039008', 
	'N0039193', 
	'N0039513', 
	'N0040294', 
	'N0040523', 
	'N0040679', 
	'N0041039', 
	'N0041658', 
	'N0041834', 
	'N0041835', 
	'N0041846', 
	'N0041892', 
	'N0042217', 
	'N0044002', 
	'N0044745', 
	'N0044974', 
	'N0044983', 
	'N0045010', 
	'N0045111', 
	'N0045326', 
	'N0045784', 
	'N0047590', 
	'N0047956', 
	'N0050058', 
	'N0050825', 
	'N0051847', 
	'N0052517', 
	'N0053011', 
	'N0053828', 
	'N0055003', 
	'N0055055', 
	'N0055164', 
	'N0055588', 
	'N0055938', 
	'N0056747', 
	'N0061586', 
	'N0070213', 
]

In [42]:
len(delete_nikkei)

345

In [58]:
group_df.shape

(5524992, 78)

In [127]:
dropped_nikkei_group_df = group_df.loc[~group_df['nikkei'].isin(delete_nikkei), :]

In [128]:
dropped_nikkei_group_df.shape

(5111337, 78)

In [129]:
for i, col in enumerate(dropped_nikkei_group_df.columns.to_list()):
    print(i, col)

0 nikkei
1 week_id
2 法人税等調整額／繰延税金費用
3 その他営業外費用
4 その他営業外収益
5 営業利益
6 その他流動資産／その他の金融資産
7 その他流動負債／その他の金融負債
8 有形固定資産の売却による収入
9 営業外費用
10 非支配株主に帰属する当期純利益
11 固定資産の売却による収入
12 その他特別利益
13 その他無形固定資産／その他無形資産
14 投資有価証券の取得による支出（▲）
15 投資その他の資産の売却による収入
16 その他の流動資産の減少額（▲増）
17 その他の小計欄より上の営業キャッシュフロー
18 上場フラグ
19 発行済株式数
20 １株当たり配当金
21 時価総額
22 PER
23 EPS
24 PBR
25 BPS
26 PSR
27 SPS
28 EV
29 CFPS
30 PCFR
31 EBITDA
32 EV/EBITDA
33 内部留保
34 サスティナブル成長率
35 配当性向
36 ROE
37 ROA
38 自己資本比率
39 流動比率
40 固定比率
41 総資産回転率
42 株主資本回転率
43 ギアリング比率
44 フリーキャッシュフロー
45 売上高・営業収益の増加額
46 売上総利益の増加額
47 営業利益の増加額
48 経常利益／税金等調整前当期純利益の増加額
49 売上高総利益率
50 売上高営業利益率
51 売上高経常利益率
52 流動資産率
53 固定資産率
54 現金及び現金同等物の増加額
55 純有利子負債
56 open
57 weekly_high
58 weekly_low
59 close
60 SMA_5
61 SMA_15
62 SMA_40
63 RSI_26
64 RSI_14
65 RSI_9
66 MACD
67 MACD_signal
68 MACD_hist
69 STC_fk
70 STC_fd
71 MOM_10
72 BB2U
73 BB1U
74 BB1L
75 BB2L
76 anomaly
77 anomaly_score

In [130]:
dropped_nikkei_group_df.iloc[:, 2:56].replace(0, np.nan, inplace=True)

In [131]:
state_df = dropped_nikkei_group_df.count() / len(dropped_nikkei_group_df[dropped_nikkei_group_df['上場フラグ'] == 1])

In [133]:
state_df = state_df.reset_index()
state_df.columns = ['feature', 'state']

In [134]:
state_df.to_csv('feature_state.csv', index=False)

In [135]:
new_order = ['nikkei', 'week_id'] + [col for col in dropped_nikkei_group_df.columns.to_list()[2:-2] if col != '上場フラグ'] + ['上場フラグ', 'anomaly', 'anomaly_score']
len(new_order)

78

In [136]:
dropped_nikkei_group_df = dropped_nikkei_group_df[new_order]

In [138]:
def group_filling_func(group: pd.DataFrame):
    print('\r', f'Filling missing values for group: {group.name}', end=' ')
    anomaly_mask = group['anomaly'] == -1
    group.loc[anomaly_mask, group.columns.to_list()[2:56]] = np.nan
    group.loc[group['上場フラグ'] == 1, group.columns.to_list()[2:56]] = group.loc[group['上場フラグ'] == 1, group.columns.to_list()[2:56]].interpolate()
    group.loc[group['上場フラグ'] == 1, group.columns.to_list()[2:56]] = group.loc[group['上場フラグ'] == 1, group.columns.to_list()[2:56]].fillna(group.loc[group['上場フラグ'] == 1, group.columns.to_list()[2:56]].mean())
    group.loc[group['上場フラグ'] == 1, group.columns.to_list()[2:56]] = group.loc[group['上場フラグ'] == 1, group.columns.to_list()[2:56]].fillna(0)
    if group.loc[group['上場フラグ'] == 1, group.columns.to_list()[2:56]].isnull().sum().sum() > 0:
        raise ValueError(f'{group.name} has NaN in {feature} after filling.')
    group = group.drop(columns=['anomaly', 'anomaly_score'])
    return group

In [139]:
drop_nan_group_df = (
    dropped_nikkei_group_df
    .groupby('nikkei')
    .apply(group_filling_func)
)

 Filling missing values for group: N0091607

C:\Users\Ito Yuki\AppData\Local\Temp\ipykernel_6764\3655470565.py:4: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  .apply(group_filling_func)

In [140]:
drop_nan_group_df.count()

nikkei            5111337
week_id           5107074
法人税等調整額／繰延税金費用    3187708
その他営業外費用          3185510
その他営業外収益          3316630
                   ...
BB2U              2532503
BB1U              2532503
BB1L              2532503
BB2L              2532503
上場フラグ             2532503
Length: 76, dtype: int64

In [146]:
tmp_drop_nan_group_df_state = drop_nan_group_df.count() / len(drop_nan_group_df[drop_nan_group_df['上場フラグ'] == 1])

In [147]:
tmp_drop_nan_group_df_state.to_csv('tmp_feature_state_after_filling.csv', index=True)

In [144]:
drop_nan_group_df.loc[drop_nan_group_df['上場フラグ'] != 1, '法人税等調整額／繰延税金費用':'純有利子負債'] = np.nan

In [145]:
drop_nan_group_df.count()

nikkei            5111337
week_id           5107074
法人税等調整額／繰延税金費用    2532503
その他営業外費用          2532503
その他営業外収益          2532503
                   ...
BB2U              2532503
BB1U              2532503
BB1L              2532503
BB2L              2532503
上場フラグ             2532503
Length: 76, dtype: int64

In [148]:
drop_nan_group_df.to_csv('../../data/main/master/product/final_feature_df.csv', index=False)